tlswg/tls13-spec

Makefile, draft-ietf-tls-tls13.md, mk-appendix.py
The appendix kept getting out of sync, so autogenerate it
=> First cut at auto-generating appendix

draft-ietf-tls-tls13.md
Just fixing up something should have been deleted in pull request #119.
=> Editorial strike reference to CCS.

draft-ietf-tls-tls13.md
Four instead of three ? (hs, alert, app_data) Allusion to CCS ... ?
Cheers,
B.
=> Another editorial strike reference to CCS.

draft-ietf-tls-tls13.md
I think I found a straggling reference to renegotiation.
=> Removing some straggling reference to renegotiation.

draft-ietf-tls-tls13.md
It refers to potentially sending a message so I would say its caps,
though I am not sure about this one ...
=> Fix some RFC keywords case

draft-ietf-tls-tls13.md
=> fix X9.62 reference link

draft-ietf-tls-tls13.md
* add back ffdhe6144
* add ffdhe_private_use range (508-511, inclusive)
=> align NamedGroup with ffdhe draft

CONTRIBUTING.md, README.md, draft-ietf-tls-tls13.md
Capitalize the first letter of the sentence like the rest of the alert descriptions.
=> a big pile of minor fixes

draft-ietf-tls-tls13.md
=> Spellcheck and trim some end line

draft-ietf-tls-tls13.md
TLS has never before done this.
=> Cite the DH paper

draft-ietf-tls-tls13.md
PR for suggestion for issue #117.
=> replace glossary with simple terms list

draft-ietf-tls-tls13.md
Merging PR 100 added to the changelog at draft-04, but we're up to draft-06 now.
=> fix changelog

draft-ietf-tls-tls13.md
RFC2119-ify a few little bits to be more clear
=> "may not" should be "MUST NOT"

draft-ietf-tls-tls13.md
- Integration of semi-ephemeral DH proposal.
- Add initial 0-RTT support
- Remove resumption and replace with PSK + tickets
- Move ClientKeyShare into an extension.
- Move to HKDF
=> Roll up all changes to semi-ephemral branch for draft-07

draft-ietf-tls-tls13.md
=> Editorialfixes

draft-ietf-tls-tls13.md
For when the WG decides it is ok...
=> Remove DSA signatures

draft-ietf-tls-tls13.md
@seanturner please confirm this matches consensus
=> Add MTI cipher suites. Fixes #32

draft-ietf-tls-tls13.md
missed one "key agreement" -> "key exchange"
=> trivial tweak

draft-ietf-tls-tls13.md
=> Consistency for the use of _RESERVED keyword (Issue #281)

draft-ietf-tls-tls13.md
Fix spacing to match other flow charts & fix one KeyShare->KeyShareEntry that was missed.
=> minor KeyShare renaming followup fixes

draft-ietf-tls-tls13.md
etc. in an example or after such as can be removed.
=> Removing some unnecessary etcs.

draft-ietf-tls-tls13.md
I found another spot that was missed in the renaming of the renaming.
=> another KeyShare rename

draft-ietf-tls-tls13.md
This has been unused since draft-07.
=> drop Boolean definition subsection

draft-ietf-tls-tls13.md
=> Reorder HkdfLabel. Fixes #330

draft-ietf-tls-tls13.md
This was one giant figure before now.
=> Contributors section cleanup

.gitignore, Makefile
So I modified the template to support the idea of having preprocessing.  This updates the makefile.
You should be able to create a diff now.
=> The preprocessor was messing things up

draft-ietf-tls-tls13.md
=> More explicitly require group matching between 0-RTT and 1-RTT

draft-ietf-tls-tls13.md
This should be "chose" not "choosed", which isn't really an accepted word.
=> minor fixes

draft-ietf-tls-tls13.md
=> Assign some code points for the new extensions

draft-ietf-tls-tls13.md
Change ticket_lifetime_hint to ticket_lifetime and add stricter requirements.
=> Proposal to change session ticket lifetime

draft-ietf-tls-tls13.md
Fix the alignment in the Handshake switch. Just a whitespace patch.
=> fix whitespace

draft-ietf-tls-tls13.md
=> Define exporter. Fixes #282

draft-ietf-tls-tls13.md
WIP PR for adding a "context" string when we resume
=> Wip context for resumption

draft-ietf-tls-tls13.md
First cut at a new, more linear key schedule. WIP so possible I missed something serious.
@martinthomson @bifurcation, comments, please? Does this seem more straightforward
=> Wip new key schedule

draft-ietf-tls-tls13.md
=> Cookie for hrr

draft-ietf-tls-tls13.md
=> Add krose to contributors

draft-ietf-tls-tls13.md
Nitpick I noticed while reading through the spec again.
=> Minor typo

draft-ietf-tls-tls13.md
I would actually much rather we only offer one PSK identity since TLS 1.2 was perfectly fine offering just one and resumption has no use for offering multiple, but I suspect I will lose that fight. Absent that, at least make the protocol well-defined.
---
Unlike both TLS 1.2 resumption and TLS 1.2 PSK, TLS 1.3 increases the state
space and allows clients to offer multiple PSK identities. This mostly works,
but 0-RTT presumes that only one is offered. Define 0-RTT to presume the first
identity is selected and clarify that other shapes are possible due to the
increased state space.
=> Define the interaction between 0-RTT and multiple PSK identities.

draft-ietf-tls-tls13.md
and arguably should never be used in that fashion.
I know that this stuff badly needs a rewrite, but this is just egregious.
=> It really can't be used without encryption now, 

draft-ietf-tls-tls13.md
Trivial cleanup of a cleanup of a cleanup. Yay typos. :p
=> trivial typo fix

draft-ietf-tls-tls13.md
This is just a WIP and needs review.
@martinthomson @grittygrease @davidben PTAL.
@davidben: I know you don't like the indication from the server but would like your opinion on other aspects.
=> WIP: Refactor negotiation as discussed in Berlin

draft-ietf-tls-tls13.md
Just saying "small allowance" is not very clear, so supply some
concrete text with an arbitrarily selected value for discussion.
Some (but not much) previous discussion in the vicinity of https://www.ietf.org/mail-archive/web/tls/current/msg20566.html
=> Supply guidance on the magnitude of replay window

draft-ietf-tls-tls13.md
Some suggested nits for s1: adding a semi-colon and swapping two whichs for thats.
=> Fixing some nits in s1.

draft-ietf-tls-tls13.md
I asked Magnus and he said to change his affiliation.
=> Changing Magnus' affiliation.

draft-ietf-tls-tls13.md
A potential minor tweak to the 1st para in s2.
=> Tweaking s2 1st para.

draft-ietf-tls-tls13.md
=> Fixing some nits in s2.

draft-ietf-tls-tls13.md
Pretty sure that we want this required to use 2119-language.
=> 2119ing the required in s4.2.1.

draft-ietf-tls-tls13.md
reading standards is hard enough without use of advanced English, use simple words
=> simplify used language

draft-ietf-tls-tls13.md
Fixing minor layout and syntax problems.
=> Layout and syntax

draft-ietf-tls-tls13.md
ClientHello.version -> ClientHello.legacy_version
=> Fix error in Version Extension

draft-ietf-tls-tls13.md
=> Add Xiaoyin Liu to contributors

draft-ietf-tls-tls13.md
Folks have already gotten this wrong, so add a note here.
=> Add guidance for draft versions on the anti-downgrade mechanism.

draft-ietf-tls-tls13.md
Response to https://github.com/tlswg/tls13-spec/issues/627#issuecomment-248734788
=> Adding me to the contributor list.

draft-ietf-tls-tls13.md
Normalize the case of "Application data" into "Application Data".
=> "Application data" -> "Application Data"

draft-ietf-tls-tls13.md
To fix #630, let's add some explanations to Section 3.
=> Clarifying syntax

draft-ietf-tls-tls13.md
This patch fixes wrong numbers of spaces.
=> fixing wrong spaces.

draft-ietf-tls-tls13.md
Some extension names are incorrect.
=> fixing typos.

draft-ietf-tls-tls13.md
This section is empty. I think this should be removed.
=> removing an empty section.

draft-ietf-tls-tls13.md
This extension is now empty. Minor cleanup.
=> minor cleanup Early Data Indication

draft-ietf-tls-tls13.md
=> [Editorial] Capitalize "not"

draft-ietf-tls-tls13.md
=> Remove unncessary key derivation stage making RPSK from RMS

draft-ietf-tls-tls13.md
=> fixing a typo.

draft-ietf-tls-tls13.md
The current text works, but tweaking it to be more general for issue #746 is simple.
=> minor tweak for issue #746

draft-ietf-tls-tls13.md
This commit fixes several typos.
=> Typofixes.

draft-ietf-tls-tls13.md
as suggested in https://github.com/tlswg/tls13-spec/pull/778#issuecomment-262873982
=> add kazuho to acknowledgements

draft-ietf-tls-tls13.md
=> Add Missing certificate_required on IANA change

draft-ietf-tls-tls13.md
=> Make enum formatting consistent

draft-ietf-tls-tls13.md
=> Add myself to contributors

draft-ietf-tls-tls13.md
=> Text for automatic replay

draft-ietf-tls-tls13.md
De-camelize Cloudflare in acknowledgements.
=> CloudFlare -> Cloudflare

draft-ietf-tls-tls13.md
I think this explanation is missing.
=> Adding a missing description for "identity".

draft-ietf-tls-tls13.md
split out into a separate pull request per @martinthomson 's comment.
=> Add kaduk to Contributors

draft-ietf-tls-tls13.md
As asked in PR#798, here is a PR to add my name to the list.
By the way, thank you @ekr for the rewrite of my rewrite, which is clearer and shorter.
=> Add Olivier Levillain (ANSSI) to the contributors list.

draft-ietf-tls-tls13.md
=> Reference rekeying paper

draft-ietf-tls-tls13.md
@davidben @martinthomson @FiloSottile 
Here's a first attempt at state machine. I did look at doing the post-handshake messages, but I think it actually destroys information because it's  mostly like "here is a message, now just go back to CONNECTED"
=> First cut at providing a state machine.

draft-ietf-tls-tls13.md
@prosecco, @adl: can you please double-check this. I had to remove all the accents, so maybe there is a better transliteration?
=> Add citation for miTLS record layer paper.

draft-ietf-tls-tls13.md
minor additions, the **context string** wasn't explained anywhere as well so I thought a mini-line would help.
=> more info on certificate verify signature format

draft-ietf-tls-tls13.md
Add an entry in the list of contributers
=> Add Jens Guballa as a contributer

draft-ietf-tls-tls13.md
confirmed in the face-to-face conversation.
=> removing an unnecessary word.

draft-ietf-tls-tls13.md
Was already present for server; add it for client.
Add me to contributors (if appropriate)
=> Add OCSP to cert extensions

draft-ietf-tls-tls13.md
Found using [mwic](http://jwilk.net/software/mwic).
=> Remove duplicated word

draft-ietf-tls-tls13.md
Add reference to label format in 5705. address issue #873 #873
=> 5705 format ref

draft-ietf-tls-tls13.md
(This doesn't break ticket_age_add because it's additive.)
=> obfuscated_ticket_age can also update on HRR.

draft-ietf-tls-tls13.md
https://github.com/tlswg/tls13-spec/pull/895#issuecomment-284526379
=> Add myself as contributor

draft-ietf-tls-tls13.md
=> Tidy up singular vs. plural session keys.

draft-ietf-tls-tls13.md
=> Warn about eternal ticket extension. Fixes #871

draft-ietf-tls-tls13.md
I think this addresses the issue raised by Russ Housley without changing the semantics of the protocol.
=> Clarify the relationship between PSK and certificates. Closes #870

draft-ietf-tls-tls13.md
Mention the assumptions going into the quoted number.
Also fix a typo.
viz. comments on #949
=> Tweak guidance on clock skew window

draft-ietf-tls-tls13.md
See discussion on https://github.com/tlswg/tls13-spec/commit/5b37a40
=> Bigger caveat for 0-RTT data

draft-ietf-tls-tls13.md
Some additions/modifications to https://github.com/tlswg/tls13-spec/pull/951 changes
Fixes https://github.com/tlswg/tls13-spec/issues/911
=> Add references to published analyses

draft-ietf-tls-tls13.md
As suggested by Nikos, provide a formal description of the point format
modelled on 4492-bis.
=> Formal representation of point format. Fixes #943.

draft-ietf-tls-tls13.md
Original by Ben Kaduk. Substantial rewrites by EKR.
@ben.kaduk: PTAL
=> Add sections on traffic analysis and side-channels.

draft-ietf-tls-tls13.md
=> updating reference for obsoleted normative reference

draft-ietf-tls-tls13.md
The "Because ..." sentence seemed like it should be combined with the next sentence.
=> making two sentence one

draft-ietf-tls-tls13.md
=> moving reserved values for hash/sig algorithms registry

draft-ietf-tls-tls13.md
Just a minor editorial correction.
=> Editorial, verb added

draft-ietf-tls-tls13.md
per https://github.com/tlswg/tls13-spec/issues/1001#issuecomment-299308476
=> Add contrib ACK for Colm MacCarthaigh

draft-ietf-tls-tls13.md
=> Cite ALPN on first mention

draft-ietf-tls-tls13.md
=> Editorial review

draft-ietf-tls-tls13.md
=> Add Steven and myself to the acknowledgements section

draft-ietf-tls-tls13.md
Be explicit that vectors are allowed in structures.
=> Allow vector fields in structures.

draft-ietf-tls-tls13.md
We never need embedded nor anonymous structs, so remove them from the
presentation language.
=> Remove embedded and anonymous structs.

draft-ietf-tls-tls13.md
See https://github.com/tlswg/draft-ietf-tls-iana-registry-updates/pull/26
=> Reserve NamedGroup(0)

draft-ietf-tls-tls13.md
This isn't necessarily any better, but it's an option.  I didn't want to lose this from my edit buffer, so you can have it.
=> Unclutter the server state machine

draft-ietf-tls-tls13.md
=> Refer to this document as opposed to 5246 for signature_algorithms

draft-ietf-tls-tls13.md
Let's make protocol overview simpler.
=> removing duplicated verification criteria in favor of Section 4.2.10.

draft-ietf-tls-tls13.md
=> fix Backward Compatibility section paragraph

draft-ietf-tls-tls13.md
Add Chris A Wood to contributors for his text on vending multiple tickets (PR 1094)
=> Add Chris A Wood to contributors for his text on vending multiple tickets

draft-ietf-tls-tls13.md
Fixes section number which describes transcript hash
=> Fixes section number referencing transcript hash

draft-ietf-tls-tls13.md
Previous PR plus some cleanup.
=> Additional data

draft-ietf-tls-tls13.md
Based on Saravanan's comments.
=> removing double and and the

draft-ietf-tls-tls13.md
if I am understanding correctly the nature of the complaint.
=> One more item from Ben (Campbell)'s review

draft-ietf-tls-tls13.md
This pull request just reformats two of the handshake diagrams to match the rest of the draft, namely, removing blank lines and aligning the arrow with the last line of the packet it relates to.
=> Editorial changes

draft-ietf-tls-tls13.md
My sense of the discussion on the list (and talking to the chairs) is that there is not consensus to make a change. This just attempts to document the situation.
=> Explain identity exposure attack

draft-ietf-tls-tls13.md
Add missing brace for first paragraph of 4.6.1.
=> Editorial: Add missing brace.

draft-ietf-tls-tls13.md
=> Fix "the the" typo

draft-ietf-tls-rfc8446bis.md
While we're renaming these anyway, exporter_secret and resumption_secret
are just as descriptive. Closes #1200.
=> Shorten some unnecessarily long names.

draft-ietf-tls-rfc8446bis.md
=> Adding Nimrod Aviram as a contributor.

draft-ietf-tls-rfc8446bis.md
=> Resumption is allowed before the initial connection is closed

draft-ietf-tls-rfc8446bis.md
The paragraph "This document supersedes and obsoletes previous" in the introduction also needs to be updated...
=> Updates and obsolete in abstract

draft-ietf-tls-rfc8446bis.md
=> Clarify unsolicited

draft-ietf-tls-rfc8446bis.md
=> Reusing key shares enables  client and server tracking

draft-ietf-tls-rfc8446bis.md
I think it would make sense to give more guidance on what to do when the connection closes.
#1281
=> #1281 describe effects of creating new long-term keys

draft-ietf-tls-rfc8446bis.md
- Change "should" -> "SHOULD" around user_canceled
- Replicate the 8773 language to another place where external PSKs is discussed.
- Remove an OPEN ISSUE marker
=> Update the changelog

draft-ietf-tls-rfc8446bis.md
I believe we are asking IANA to also update all references to "this RFC".
=> IANA tweak

draft-ietf-tls-rfc8446bis.md
=> (EC)DHE instead of EC(DHE)

draft-ietf-tls-rfc8446bis.md
=> Fix a missed name change.

draft-ietf-tls-rfc8446bis.md
=> Add changelog entry for CertificateRequest. Fixes #1311

.gitignore, draft-ietf-tls-rfc8446bis.md, package.json
=> Use aasvg for pictures

draft-ietf-tls-rfc8446bis.md
=> Address erratum 5717

draft-ietf-tls-rfc8446bis.md
=> IDnits: s/MUST not/MUST NOT

draft-ietf-tls-rfc8446bis.md
=> Update 6125bis ref

draft-ietf-tls-rfc8446bis.md
=> More generic recommendation for CSPRNG.

draft-ietf-tls-rfc8446bis.md
This is a revised version of the text from @ms-s in #1366 that I think makes the point more sharply.
=> Rpk misbinding

draft-ietf-tls-rfc8446bis.md
Editorial updates to references
=> Editorial updates to references

draft-ietf-tls-rfc8446bis.md
See: 
https://github.com/tlswg/draft-ietf-tls-esni/pull/641/files
=> Clarify the use of HKDF-Expand-Label.

draft-ietf-tls-rfc8446bis.md
Hash algorithm negotiated by the peers in cipher suite is also used in Transcript-Hash.
=> Hash in Transcript-Hash
