- draft-ietf-tls-tls13.md
These don't use ephemeral Diffie-Hellman:
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_256_GCM_SHA384
> Cipher suite without ephemeral Diffie-Hellman.

- draft-ietf-tls-tls13.md
A straightforward cleanup of part of the backwards compatibility section. (handles an easy part of issue #54) SSL 2.0 backwards compatibility was previously deprecated in TLS 1.2 (2008) and was warned to be "phased out with all due haste". RFC 6176 (2011) prohibits it entirely. It's a section of obsolete complexity still in the draft. Remove it and replace it with a simple "MUST NOT" send or accept.
-----
Edit to correct attribution of the "phased out with all due haste" language. Whilst in the TLS 1.2 (2008) spec, it was first introduced in SSL 3 (1996). It has been around for 19 years, not 5.
> remove SSL 2 backwards compatibility section & prohibit SSL negotiation

- draft-ietf-tls-tls13.md
The TLS 1.2 RFC cited WIP extension definitions at time of publish. Update current draft to point the final RFC 6066.
> update TLS extensions ref (fix issue #139)

- draft-ietf-tls-tls13.md
These two notes are leftover from TLS 1.2 and not needed anymore in TLS 1.3. The first may not even be valid anymore.
> remove obsolete change from TLS 1.1 notes about signature algorithms

- draft-ietf-tls-tls13.md
This does the following:
1) Reorganize the backwards compatibility section into subsections for easier readability
2) Freezes the ClientHello record layer version to TLS 1.0 (its effective compatible version)
3) Adds explicit requirement that all other record layer versions match the negotiated version
This plus PR #105 should be sufficient to close issue #54.
The record layer requirements were proposed by Brian Smith on the list.
http://www.ietf.org/mail-archive/web/tls/current/msg14870.html
(also mentioned by him in other discussions)
> revise backwards compatibility & fix record layer version

- draft-ietf-tls-tls13.md
I have seen multiple implementations with messages marked as warning instead of fatal..
It might be more explicit this way ?
B.
> Improve alerts enums with error type as comments

- draft-ietf-tls-tls13.md
Sometimes the alert name is in between quotes like : "protocol_version" alert ..
and sometimes it is not ... like : close_notify alert
> Fix alert names when referred to

- draft-ietf-tls-tls13.md
More clear if the exact field names are used properly, instead of the *.version naming that might be confusing.
> use full hello message version field names

- draft-ietf-tls-tls13.md
They're not used anywhere in the document anymore.
> drop obsolete references

- draft-ietf-tls-tls13.md
Expands on @beurdouche's improvements. The obsolete alerts were previously fatal and still are. Mark them as such.
Also fix one of their names which is missing the "_RESERVED" in the descriptions list.
> fix alert name & label obsolete alerts as fatal

- draft-ietf-tls-tls13.md
A newer recommendation could be put in as a replacement, however I don't think the sentence adds anything to the explanation, nor do I expect whatever could be recommended to hold up forever.
Also fix some punctuation in the same paragraph.
> drop obsolete recommendation of 1024-bit DHE as secure

- draft-ietf-tls-tls13.md
Removal of the glossary re-assigned the appendix letters, so the ones referenced here are all one earlier.
> fix security considerations

- draft-ietf-tls-tls13.md
The last thing citing it was the glossary, which was recently removed.
> remove obsolete SCH reference

- draft-ietf-tls-tls13.md
Small editorial change: The document currently goes back and forth between "SSLv3" & "SSL 3.0". Stick with the latter for consistency and clarity.
> depict SSL 3.0 version consistently

- draft-ietf-tls-tls13.md
Travis warns about them as they don't get wrapped in the final build and end up being too long. See the plaintext version here:
https://www.ietf.org/id/draft-ietf-tls-tls13-07.txt
> fix line widths of handshake flow legends (fix Travis warning)

- draft-ietf-tls-tls13.md
Use refs for HKDF & HMAC in the document and drop the unused AES CBC RFC ref in favor of the AES GCM RFCs (refs already in use).
Caught via Travis warnings that they were all unused. It also notes that RFC 2246 (TLS 1.0) isn't referenced directly and RFC 5705 isn't used, either.
@ekr: You probably wanted to reference RFC 5705 somewhere in your recent work, but it's not currently used. Travis also complains about I-D.ietf-tls-session-hash, though that is referenced in the credits. It probably should be referenced somewhere too.
> update RFC refs

- draft-ietf-tls-tls13.md
Some fixes for things I didn't catch when I checked for typos in the big patch last time. Of note, you're missing a closing brace for the select in "PreSharedKeyExtension" and a semicolon after "KnownConfigurationExtension". I also corrected things to match the existing (admittedly unusual) indentation style of the document and put quotes around the extension IDs you missed. (some had them; some didn't)
> fix indentation and some missing notation

- draft-ietf-tls-tls13.md
Not sure if the deprecation cutoff will be at 224 bits (~112 bit security level) or 255 bits (~128 bit security level) yet, so I've just done the former for now.
This drops the old curves under 224 bits, updates the extension example bytes, and deprecates MD5.
> Deprecate old curves, MD5, & SHA-224 (for issue #186)

- draft-ietf-tls-tls13.md
This revises "The Cipher Suites" section to simplify redundant language, actually explain the de facto naming convention, and add all currently available AEAD cipher suites. It also drops the appendix table that has already had its section whittled down quite a bit, in favor of the explanation and new table in the main section.
Note that this is all of the AEAD ciphers available in the current IANA registry [0], plus ChaChaPoly (which has to be a normative reference [1], so must reach RFC status before this does). Issue #53 just said "standards track AEAD ciphers", but as the registry lists them all, adding them wasn't difficult. If we'd rather not cite them here then they can of course be cut out (ARIA, Camellia, & ECDHE AES-CCM are informational; the rest are standards track, including …
> revise cipher suites section (fixes issue #53)

- draft-ietf-tls-tls13.md
It appears to be the consensus that sect571r1 should be dropped.
This drops it and adds placeholders for the CFRG curves. There are likely to be more than these two values in the final version to indicate ECDHE & certificate usage separately.
> drop support for sect571r1

- draft-ietf-tls-tls13.md
Fixes for this keep showing up in other patches due to being caught near the changed area or being automatically fixed by a text editor. Just fix everything at once now, rather than cluttering up future changesets. (patch produced automatically via text editor)
> fix all trailing whitespace

- draft-ietf-tls-tls13.md
Since Client Key Share is an extension now, it's listed in the extensions section. However, it currently is missing a "#" from its section headers causing the numbers to restart from there down until the next header of that depth.
https://tlswg.github.io/tls13-spec/#client-key-share
Current:
6.3.1.4. Hello Extensions
6.3.1.4.1. Signature Algorithms
6.3.1.4.2. Negotiated Groups
6.3.1.5. Client Key Share
6.3.1.5.1. Diffie-Hellman Parameters
6.3.1.5.2. ECDHE Parameters
6.3.1.5.3. Known Configuration Extension
6.3.1.5.4. Pre-Shared Key Extension
6.3.1.5.5. Early Data Indication
6.3.1.5.5.1. Replay Properties
6.3.2. Server Key Share
Correct:
6.3.1.4. Hello Extensions
6.3.1.4.1. Signature Algorithms
6.3.1.4.2. Negotiated Groups
6.3.1.4.3. Client Key Share
6.3.1.4.3.1. Diffie-Hellman Parameters …
> fix broken section numbering ("Client Key Share" and all subsequent extension sections)

- draft-ietf-tls-tls13.md
Trivial fix. Just a missing '}' character.
> fix broken cross-reference link

- draft-ietf-tls-tls13.md
Just a few things I noticed that I think make it a little bit easier to follow.
* Name resumption_secret consistently when used
* Show full legend for each handshake flow
* Simplify/clarify secret sources table a bit and make text cases consistent
The resumption secret naming was also apparently noticed by @martinthomson in issue #191.
(Edited to note: this PR has been pruned down to a smaller list of changes; see commit message)
> fix spacing & minor tweaks for secrets

- draft-ietf-tls-tls13.md
As discussed on list.
Closes #55.
> Reducing AEAD expansion to a maximum of 256 bytes

- draft-ietf-tls-tls13.md
@ekr: Quick PR for fix noted for PR #218 plus a couple other small nits.
* Still on draft 08.
* Fix a typo. ("permittion" is not a word)
* Consistently use spaces around the "+" in "2^14 + 256". (some did; some didn't)
> small fixes for changelog and spacing

- draft-ietf-tls-tls13.md
Consistently capitalize AEAD, fix a missing period, and fix a typo in a comment (for the sole purpose of appeasing my perfectionist tendencies ;).
> very trivial fixes

- draft-ietf-tls-tls13.md
This is a set of changes covering mailing list discussions about error alerts, certificate acceptance, SHA-1 deprecation, as well as including some recommendations about curves. There's also quite a few other little fixes mixed in there, including some cleanups in RFC2119 language. The alerts list has been fully updated to include all standardized alerts (PSK alert is needed for new PSK extension, in particular). This also adds RFC 5746 ("renegotiation_info" info extension) to the list of newly obsoleted RFCs, as renegotiation has already been removed completely thus making it no longer applicable as of this new TLS version.
PR #169 has the discussed change to certificate ordering requirements, however it is waiting on @seanturner to assess consensus so I'm not including it here.
(Edited …
> MTI Extensions (incl. issue #116)

- draft-ietf-tls-tls13.md
Current client implementations allow more flexible certificate ordering than the spec allows and some server implementations send certificates in orders that the spec says "MUST" not be done. Relaxing the language here to a "SHOULD" is appropriate so implementers following this spec know that such situations need to be handled. Enforcing this more strictly would cause interop problems for no practical gain.
The modified language here is based on the mailing list discussion.
> relax certificate_list ordering requirements to match current practice

- draft-ietf-tls-tls13.md
Modified extension requirements based on recent list discussion. It's a little verbose with repeated boilerplate, but it's clear no matter which section you read now. I've also moved the relevant requirements up top to a consistent place for each extension's section.
The level of strictness here is now:
* If attempting to negotiate and the mandatory extension isn't available: MUST error
* If just detecting an invalid combination, but not actively negotiating: MAY error
* SNI is clearly listed as MUST support, servers MAY require, and SHOULD error if required
* The "unsupported_extension" alert is reworded more generally and put in as the consequence for violating the pre-existing "MUST NOT" send the client-only extensions from a server requirements. Also added some more, namely the fact …
> expand MTI Extensions and add more strict requirements

- draft-ietf-tls-tls13.md
Missing semi-colon in the message definition.  Also, the signature_algorithms of the client are what matter.
> Fixing Server Certificate Verify nits

- draft-ietf-tls-tls13.md
The current wording at the end of the section on resumption and PSK should be changed to indicate that if a server declines resumption then a full handshake, including the server Certificate and CertificateVerify messages, should take place. In its current state, the comment on omission of these messages is not disjoint from the statement regarding the server's rejection of resumption.
> Suggested wording change to Resumption and PSK section.

- draft-ietf-tls-tls13.md
SNI is now MTI (all MUST support; clients SHOULD send when applicable; servers MAY require it)
Thus, RFC 6066 in which it is defined is now a normative reference, not informative.
https://www.ietf.org/iesg/statement/normative-informative.html
> promote RFC 6066 to normative reference

- draft-ietf-tls-tls13.md
Missed that when rebasing. sry.
> Minor fix of syntax for SigAlg enum

- draft-ietf-tls-tls13.md
The current min size of HkdfLabel.label is impossible. Here's a PR for a trivial fix by increasing it.
HkdfLabel.label = "TLS 1.3, " + Label
("TLS 1.3, ").length = 9
if Label.length >=1 then
HkdfLabel.label.length >= 10
It can never be 8 or 9 bytes long.
next power of two is 16, so might as well do:
opaque label<16..255>;
which has 9 bytes for version prefix & a minimum of 7 for the label (current shortest is 15 bytes)
> fix HkdfLabel.label min length

- draft-ietf-tls-tls13.md
Remove self-signed, since the key point is that it's a trust anchor that was independently distributed.  Note here that some trust anchors are signed, though that usually indicates a reason for it to be included, the signing might persist for longer than the actual need for it.
Also the explanation had more words than it needed.
n.b., I only loosely wrapped this stuff, if you want a proper wrapping of lines, name a preferred wrap column, because I couldn't work out what to do here.
> Copy edit certificate_list changes

- draft-ietf-tls-tls13.md
This is stated to exist in the definition for "signature", however the value wasn't actually added to the enum. ( https://github.com/tlswg/tls13-spec/pull/265/files#diff-9d84740dcc569a0a5a359d0fba461a05R2286 )
> fix missing RSA-PSS SignatureAlgorithm value

- draft-ietf-tls-tls13.md
This completes the removal of SHA-1 for CertificateVerify. There's no reason to allow it there at all
> Forbid SHA-1 in CertificateVerify

- draft-ietf-tls-tls13.md
The struct contains a value named handshake_hash, not session_hash.
I apparently had fixed this in PR #189. Pulling it out separately to get it in now, as it hasn't even been decided for sure if we're doing that.
> fix misnamed handshake_hash in text

- draft-ietf-tls-tls13.md
This PR includes CertificateRequest changes discussed at the TLS WG Interim:
1. Removes certificate_types, which are no longer needed.
2. Adds client cert selection by certificate extension values. This helps make CertificateRequest more specific and eliminate the need for the confusing "Choose a certificate" UI.
> Removing certificate_types and adding certificate_extensions

- draft-ietf-tls-tls13.md
Fix another missing brace breaking a link.
Also drops a leading space for that line; markdown doesn't seem to need it and generates a space there anyway, just as it does for all the other lines.
> fix broken reference link

- draft-ietf-tls-tls13.md
I think that the decision was to make this mandatory, since present-but-empty is harder to screw up.
Closes #323.
> EncryptedExtensions is mandatory

- draft-ietf-tls-tls13.md
This addresses Brian's comment from #293. We don't use "octet length" anywhere else in the document.
> Use "length" instead of "octet length"

- draft-ietf-tls-tls13.md
The spec always uses the gender-neutral possessive pronoun "its" for "client", so I think we should definitely fix that occurrence.
Also, it seems that throughout the document we try to not use gender-specific pronouns for "attacker". I'm not sure about "their" though, as it looks like we usually try to avoid that by restructuring sentences, but I may be mistaken. We could also refer to multiple attackers?
> Use correct pronoun for "client" and "attacker"

- draft-ietf-tls-tls13.md
The early_data extension should be listed as one of the few that can't go into EncryptedExtensions but must be sent with ServerHello.
> EarlyDataIndication response must be sent with ServerHello

- draft-ietf-tls-tls13.md
An errant 's' got into one of the field names from one of the draft versions of the unified KeyShare extension. Quick fix to match the name defined in the struct.
This PR also contains couple other trivial typo fixes.
> typo fixes

- draft-ietf-tls-tls13.md
When talking about handling downlevel clients, the spec variously says a server "MAY" receive such messages, or "may" receive such messages.  Since this is discussing a possibility (not a permitted behavior), the normative language isn't correct; lower-case versions of the RFC2119 terms have the potential to confuse readers.  Suggest changing all of these to "might" to denote a possible occurrence server implementers will need to handle.
> Receiving TLS 1.2 ClientHello:  MAY/may to might

- draft-ietf-tls-tls13.md
This section has a strange table that looked a little messy.  So I cleaned that up.  However, I noticed that it used to say this:
> The certificate MUST allow the key to be used for signing (i.e., the
digitalSignature bit MUST be set if the key usage extension is present) with
the signature scheme and hash algorithm that will be employed in the server's
KeyShare extension.
Which doesn't make any sense.  Should this be signature_algorithms extension instead?
> Server certificate selection

- draft-ietf-tls-tls13.md
I included limitations on the amount of data to send, for AES-GCM and ChaCha20-Poly1305. We don't seem to have rekeying capabilities in this branch, but some editing should fix that.
> Include data volume limitations

- draft-ietf-tls-tls13.md
I noticed that the doc was almost consistently refering to the `KeyShare extension` where everywhere else, the text used `"signature_algorithms" extension`.  I changed everything I found to the latter, except those hit by #367, because that will conflict if that is merged.
> More consistently name extensions

- draft-ietf-tls-tls13.md
The current text is a mix of omitting and sending empty, as pointed out by Ilari on the mailing list. This fixes things and switches to an always-send model.
> always require key_share extension with (EC)DHE suites

- draft-ietf-tls-tls13.md
@ekr: You addressed the main ambiguity in https://github.com/tlswg/tls13-spec/commit/74c4c7da1bf5bcea4f75cfc38c1aedb406098d3d#diff-9d84740dcc569a0a5a359d0fba461a05L2097 . This fixes a few remaining issues. An itemized list:
* "handshake_failure" alert is fatal
* note it must be appended, not just "used", in the selected_group description (just using instead of appending creates a downgrade attack due to lack of authentication for this message, as discussed previously)
* clean up styling of variable names; the dominant style uses no quotes around variable names, but quotes around enum values (granted, this may not be the ideal style, but it is more or less consistently the case elsewhere in the document)
* note that the same rule as ServerHello applies: no extensions the client did not …
> helloretryrequest fixups

- draft-ietf-tls-tls13.md
This cleans up some of the text around EarlyDataIndication that was introduced previously.
> Clean up early data indication text

- draft-ietf-tls-tls13.md
@seanturner did a massive message->alert change a while back and I did yet more when we were rebasing his patch. Looks like there's more up here in Closure Alerts.
We're referring to alerts, not the messages that carry them. Switch to "alerts" instead to remain consistent with the rest of the document, notably the following section.
> minor cleanup: message->alert in Closure Alerts

- draft-ietf-tls-tls13.md
https://www.ietf.org/rfcdiff?url2=draft-ietf-tls-chacha20-poly1305-04
A new ChaChaPoly draft was just released that changes all the cipher suite names to have an explicitly specified hash. This updates this document with the new names.
> update CHACHA20_POLY1305 cipher suite names

- draft-ietf-tls-tls13.md
The text & struct have different names for the config ID. Use the one in the struct.
> correct field name in text

- draft-ietf-tls-tls13.md
The current version is missing a word and I tried to improve it a bit more.
> Improve end_of_early_data description

- draft-ietf-tls-tls13.md
Proposed clarification based on mailing list discussion. Explicitly state that 0-RTT records MUST NOT get special treatment and 1-RTT fallback on decryption errors is prohibited. This may technically already be the intended situation, however any ambiguity here will undoubtedly lead to some implementations falling back to avoid breakage in this scenario, which risks 0-RTT data stripping attacks. As I agree with the expected behavior stated by @ekr on-list, this is just a matter of adding some clarification here (even if it might be redundant; someone interpreting the text the way I initially did could do something dangerous if they don't also notice the risk).
> explicitly prohibit 1-RTT fallback on 0-RTT data error

- draft-ietf-tls-tls13.md
One more minor fix I just noticed when diffing the latest draft. Just capitalization fixes to match the other notes.
> trivial capitalization fixes

- draft-ietf-tls-tls13.md
See the dubiously line-wrapped table here:
https://tools.ietf.org/html/draft-ietf-tls-tls13-11#page-81
The current draft 11 has the last 'd' in the "Recommended" header and all of the last 'd's for all "Encrypted"s bumped to a second line.
The ALPN extension ID name is quite long and results in things not fitting when rendered for tools.ietf.org. This commit adds a space between the name and RFC number/link to (hopefully) let it wrap and have things fit properly.
@martinthomson: Is this spacing fix enough to make the renderer used for that happy enough to wrap this column?
Note also that the cipher suites table also has issues, however I think this will all fit correctly once ChaChaPoly gets an RFC number and its reference can fit properly.
> fix extensions table in IANA considerations

- draft-ietf-tls-tls13.md
Cleaned up references to known_configuration extension (merged into early_data in draft-08)
> Substitute early_data for known_configuration

- draft-ietf-tls-tls13.md
It seems that both Karthik and I misinterpreted this "IV" to be uppercase, but it should be lowercase... Thus fixing this table so that others won't make the very same mistake..
> purpose should be lowercase

- draft-ietf-tls-tls13.md
Small simplification & clarification. Now that the server key share is in an extension, all TLS 1.3 endpoints will have at least one extension in their hello, either "key_share" or "pre_shared_key", at minimum. This changeset simplifies the ServerHello struct in the same manner as was previously done for ClientHello and adds short notes explicitly stating this.
> all hellos now have at least one extension

- draft-ietf-tls-tls13.md
(via https://github.com/tlswg/tls13-spec/commit/238bac7b94b7892c4e86bbb8e9588234ac5a2410#commitcomment-15351983)
> fixed typo, use <0..2^8-1> for consistency instead of <0..255>

- draft-ietf-tls-tls13.md
It would appear, based on the ladder diagrams that the server can't speak after sending its Finished, when it can (unless it doesn't *want* to speak because it is waiting on client auth, that is).  This changes the diagrams to show that.
This is largely editorial discretion stuff.
> 1rttappdata

- draft-ietf-tls-tls13.md
the PSK acronym occurs first in the TOC, and later in S 6 without being spelled-out -- these modest changes fix that. 
[ this is also a small test to see if I have the tlswg+github process figured out ]
> spell-out first occurances of PSK

- draft-ietf-tls-tls13.md
For issue #305.
I'm listing this as WIP for now, as the reason this has yet to be done is that we need to list the ECDHE PSK suites, which are themselves WIP. I'm citing the current draft, though it has yet to be adopted by the TLS WG. Not sure what the policy on this is; we probably don't want to merge before that's dealt with. In any case, here's a new table with the (EC)DHE PSK suites as requested in issue #305.
> enumerate supported PSK cipher suites (issue #305; WIP)

- draft-ietf-tls-tls13.md
This PR contains proposed specification text for the mailing list thread here:
https://www.ietf.org/mail-archive/web/tls/current/msg19060.html
SignatureAlgorithm and HashAlgorithm are merged into a single u16 value. Fold signing curves into it as well. This is wire-compatible with TLS 1.2, generalizes better to Ed25519 which combines all parameters into a single algorithm, and allows the server to report signature curve preferences to the client.
Per discussion, there are only three ECDSA values, one per curve, so mismatching curve and hash is no longer allowed. They use the same values as the old TLS 1.2 ECDSA code points. (If the WG decides differently here, that can be tweaked.)
Otherwise, I tried to keep SHOULD NOTs and MUST NOTs the same. MUST NOT values (MD5 and SHA-224) are …
> Revise signature algorithm negotiation.

- draft-ietf-tls-tls13.md
The current wording of KeyUpdate a bit ambiguous, and leaves out certain areas needed for enforcement and might result in a security issue if not implemented correctly
A sender of the keyupdate has no choice of which key to encrypt the keyupdate with, however the recipient does. 
It has 2 choices:
a. Use old key and reset the sequence number after acking the keyupdate
b. Use the new key for the key update and reset the sequence number before acking the keyupdate.
This distinction is very important for security. If a client uses option b), this causes a security vuln. Because the sequence numbers are reset after a key update, an attacker could truncate (application data) records from the old stream, wait for the key update from the client, and then let new packets through. The client or …
> Clarify verification requirements of KeyUpdate

- draft-ietf-tls-tls13.md
This appends a "_RESERVED" to each name for the DSA values in the SignatureScheme enum to have them hidden up top and only shown in the appendix, as they're obsolete and their full description was removed in a prior changeset (https://github.com/tlswg/tls13-spec/commit/bed72816a2cbcb2695718c3936c44b78498e07da).
The alternative would be to remove them completely and expand the obsolete_RESERVED ranges to encompass them (these ranges are already hidden up top). I think keeping them as separate reserved values in the appendix is a bit better.
Note that I have to delete this block's header comment as well, as the auto-pruning won't catch that.
> append "_RESERVED" to DSA SignatureScheme value names

- draft-ietf-tls-tls13.md
Minor editorial tweaks. I just noticed the extra line that gets left in there when shown up top (two lines between first two shown blocks, instead of one). This fixes that. Also drops the periods after the comments, as they're not sentences.
> followup tweaks to PR #434

- draft-ietf-tls-tls13.md
WIP, not ready to land. @martinthomson PTAL
> Encrypted extensions for client

- draft-ietf-tls-tls13.md
0-RTT is *not* backwards compatible because of the external application data records. Add some guidance for both clients and servers to mitigate this. Ideally the server SHOULD could be a MUST and that would be the end of it, but I do not expect all servers to get this right and so clients will want a fallback.
This also lets us provide guidance on the exact client-side fallback trigger and explicitly say not to change the version. Conveniently, there is a reliable signal available. (Historically, clients have used network errors or generic protocol errors as fallback triggers which masks new server bugs.)
> Add a section on 0-RTT backwards compatibility.

- draft-ietf-tls-tls13.md
There are many fields where unknown values are supposed to be ignored and not a fatal error. Experience with buggy TLS 1.2 servers suggests this is somehow not obvious. Switch the mention of omitting the extensions field completely (which is no longer possible) with unknown extensions.
Also explicitly call out ClientHello version processing as this historically has been a huge ecosystem failure.
> Add some more implementation pitfalls.

- draft-ietf-tls-tls13.md
TLS 1.2 did not specify this and some implementations have sporadic interoperability issues as a result. Specify that, in TLS 1.3, public keys should be zero-padded. This is believed to be the more compatible TLS 1.2 variant, and having cryptographic messages be fixed-width fields where possible (not that it matters for public keys) seems preferable to saving one byte 1/256 of the time.
> Specify whether DHE public keys are zero-padded.

- draft-ietf-tls-tls13.md
Here's a quick followup to PR #459. Both the new and old issue are applicable. Whilst TLS 1.3 will always have extensions, servers will need to be able to handle hellos from older clients that don't send any extensions without choking. "Correctly" in this case is just a matter of parsing and rejecting or replying as TLS 1.2, but it's nonetheless still applicable for interop.
> minor followup to PR #459

- draft-ietf-tls-tls13.md
(Let me know if you think this is sufficiently non-trivial that it deserves a mailing list posting. It is a wire format change, but I think a fairly boring one.)
Only the outer length prefix is necessary, not the inner one. Named groups can
just as easily take a byte string with known length rather than need to parse
fields out.
This is consistent with the definition of DigitallySigned.signature; the
signature is an opaque field which is passed as a byte string into the
corresponding signature algorithm. The definition of rsa_pss_sha256 does not
define an inner u16 length prefix. It simply takes the opaque byte string and
passes it into the rsa_pss_sha256 function.
(In fact, this change means KeyShareEntry and DigitallySigned structures
exactly parallel.)
This also fixes some references …
> Remove redundant length prefix from KeyShareEntry.key_exchange contents.

- draft-ietf-tls-tls13.md
Every other use of Diffie-Hellman preserves leading zeros. See PKCS #3 section
8.3, RFC 2631 section 2.1.2, and SP 800-56A section C.1. I assume X9.42 says
something similar to RFC 2631, but I do not have a copy of it. This discrepancy
has caused sporadic interoperability issues in TLS 1.2's DHE construction, so
clearly it's confusing.
Moreover, having variable-length secrets is generally dubious. It exposes an
unnecessary side channel.
Since TLS 1.2's server-fiat DHE and TLS 1.3's negotiated DHE are already very
different animals (1.3 DHE is more like 1.2 ECDHE than anything else), change
it to the more reasonable scheme going forward. This is not compatible with 1.2
and does risk a different set of sporadic interop issues if implementations do
not realize this changed, but we already …
> Preserve leading zeros in Diffie-Hellman secrets.

- draft-ietf-tls-tls13.md
Session tickets enable client tracking by passive observers if they are used more than once. This change adds guidance to implementors for preventing this.
> Add implementation note about client tracking

- draft-ietf-tls-tls13.md
For issue #473. This relaxes the requirement to check for and error on lack of inclusion in both extensions and focuses the explicit error requirement on the case of multiple keys for the same group.
> relax and focus error condition (issue #473)

- draft-ietf-tls-tls13.md
When I commented in #461, I mistakenly thought RFC 7231 was the first RFC in HTTP/1.1 spec series. Now I think it is better to use RFC 7230 as a reference of HTTP/1.1 in Client Tracking Prevention section, since RFC 7230 talks about connections, while RFC 7231 talks about the header fields, status codes, etc.
> Change the HTTP/1.1 reference from RFC7231 to 7230

- draft-ietf-tls-tls13.md
This change uses underscores consistently for the key/iv paramaters
to aid searching.
> Use underscores consistently for key/iv parameters

- draft-ietf-tls-tls13.md
A 0-RTT is always a PSK handshake, so it requires a pre_shared_key, make it explicit in the diagram.
Also, in 0-RTT the key_share is only sent by the server for (EC)DHE, mark it optional.
Finally, the client key_share in PSK is a SHOULD, so mark it optional.
> Make pre_shared_key explicit in 0-RTT diagram

- draft-ietf-tls-tls13.md
This is purely aesthetic, but apparently no one realizes the name is different, not even IANA, so we may as well go fix it.
(I don't know how to write IANA considerations, so I've left it a TODO. But if you give me text, I'll update this PR to include it.)
---
For consistency. At a glance, it seems most TLS implementations did not realize
the HandshakeType value was actually named session_ticket and assumed it was
named new_session_ticket anyway. Moreover, the IANA entry was named neither and
actually named NewSessionTicket since RFC 4507's IANA considerations used the
wrong name.
> Rename HandshakeType.session_ticket to HandshakeType.new_session_ticket.

- draft-ietf-tls-tls13.md
RFC 3447 refers to it as RSASSA-PKCS1-v1_5, not RSASSA-PKCS-v1_5.
> Fix typo in RSASSA-PKCS1-v1_5's full name.

- draft-ietf-tls-tls13.md
Some small tweaks and fixes for issue #478:
* Move HKDF-Extract citing to a sentence and bring HKDF-Extract with it.
* Change the Messages arg to HashValue, as the actual hashing is stated in the definition of Derive-Secret which is passing this function a hash, not messages. (fixes issue #478)
* More concise defining of HkdfLabel.
* Use the word "zeroes" instead of "0s".
Edited to add:
* Also, appended a commit to fix an extra trailing paren.
> fixes for issue #478

- draft-ietf-tls-tls13.md
The text that @davidben proposed that covered 0-RTT and backward
compatibility took the position that a server might not support
TLS 1.3 when it was attempted.  That leads to all sorts of mess,
particularly given that most 1.2 and earlier servers are totally
incapable of handling 0-RTT messages.  In NSS, it's a fatal
error and I would expect others to be similarly strict given the
smackTLS work.
This is a simpler set of rules:
* If the server advertises support for 0-RTT that means that it
commits to supporting TLS 1.3 for the duration.
* If the client attempts 0-RTT, then it should abort if it sees
a ServerHello with 1.2 or earlier.
This is stricter than what we currently have, but it's crisper.
That is, unless people imagine modifying their TLS 1.2
implementations to be able to ignore …
> Negotiating 0-RTT means that the server has 1.3 everywhere.

- draft-ietf-tls-tls13.md
Update Chacha20-poly1305 reference to RFC7905 in this document.
> Chacha20-poly1305 is now RFC 7905.

- draft-ietf-tls-tls13.md
Lack of a blank line after "draft-14" but before the bullet point causes it to render all on one line:
https://tlswg.github.io/tls13-spec/
This is just a quick patch to make the spacing consistent because apparently Markdown (or, at least whatever is interpreting it there) can be picky. ;)
This is just a whitespace fix.
> trivial formatting fix

- draft-ietf-tls-tls13.md
The sentinel value was chosen to avoid conflicting with any valid TLS 1.2
value, but this is not actually desirable. We need to avoid conflicting with
any non-TLS-1.3 server but *still* be a valid TLS 1.2 value. A TLS 1.3 server
must still correctly implement TLS 1.2 to interoperate with existing TLS 1.2
clients.
In particular, placing it at the front clobbers TLS 1.2's server timestamp.
Putting this in the random was silly and 1.3 rightfully removes it, but some
software depends on servers sending a timestamp. The tlsdate program uses this
as a secure-ish time synchronization protocol. Silly as it is, it exists and it
arguably was following the letter of the TLS 1.2 spec, even if we don't like
that timestamp very much...
Move the sentinel to the end so servers may implement this …
> Move the downgrade sentinel to the end of server_random.

- draft-ietf-tls-tls13.md
Editorial: Indented code blocks do not render correctly until after the first blank line. Added initial blank lines where appropriate to fix the appearance of affected code blocks.
> Fix code block display issues

- draft-ietf-tls-tls13.md
I'm going to see about getting rid of it anyway, but I think, for the spec, this is probably the better text, as sad as it makes me.
---
The revised signature algorithm mechanism left the {sha1, ecdsa}
SignatureAndHashAlgorithm without a corresponding SignatureScheme defined at
all. SHA-1 does not have a corresponding curve, so defining it alongside
ecdsa_p256_sha256 and friends was a nuisance.
But omitting it, combined with other text, implicitly means it "MUST NOT be
offered or negotiated by any implementation".  Clients (ideally) send only one
ClientHello, so this implies a constraint on TLS 1.2 as well. SHA-1 needs to
go, but I think I was a tad overzealous here.
I wouldn't be surprised {sha1, ecdsa} can be removed from TLS 1.2 right now.
Certainly it will be much much easier to …
> Define ecdsa_sha1 and mark it as a SHOULD NOT alongside other SHA-1 algorithms

- draft-ietf-tls-tls13.md
This sentence in general seems redundant, but if it's going to be included it should be correct.
> Specify that AEAD plaintext also includes the padding bytes.

- draft-ietf-tls-tls13.md
The section on connection states was almost all cruft.  I made a new section for nonce construction and moved the piece on sequence numbers there.
The only text I modified was the first three paragraphs of the nonce section, which needed to be scrubbed for references to "connection state", and the lead-in section on the AEAD, which I moved to where the other AEAD stuff was and expanded a little to include some forward references.
> Remove cruft from Record Layer section, reorganize a little

- draft-ietf-tls-tls13.md
https://github.com/tlswg/tls13-spec/commit/e91689832a1827bd023d8e173d3a006b0ff637b3
This recent commit left a few jumbled sentences.
> fix jumbled merge

- draft-ietf-tls-tls13.md
This is a lot of editorial work. Specifically:
- Removing redundant text
- Reordering things so that the handshake appears first and making the handshake and alert section A heds
- Harmonize a bunch of text
- Remove the obsolete Security Analysis text in preparation for providing a real Security Analysis section.
This is my first cut and I will make another pass later today to catch mistakes/things that still need to be updated.
@davegarrett @martinthomson you may want to take a look at this pre-merge.
> Restructure

- draft-ietf-tls-tls13.md
As all error alerts are now considered fatal (PR #530), we no longer need "This alert is always fatal" explicitly stated everywhere in that section.
> remove now redundant fatal alert language

- draft-ietf-tls-tls13.md
1. Code point values for Chacha/poly are no longer preliminary.
2. Update the mail list info URL.
> Some editorial updates

- README.md
Use HTTPS link for https://xml2rfc.tools.ietf.org/
> Use HTTPS link

- draft-ietf-tls-tls13.md
Noticed by Ilari Liusvaara on-list. Effective follow-up to PR #537. ChaCha/Poly is no longer preliminary, though ECDHE PSK AES still is.
> minor update to preliminary assignment note

- draft-ietf-tls-tls13.md
(My impression from the list is that we're not doing post-handshake key separation. If I'm wrong and we are, this will need to be slightly tweaked. Anyway, the current state of the world is we don't do it, so I've worded it accordingly.)
---
As the Finished message is an implicit ChangeCipherSpec, it's worth
clarifying that this is the point at which the cipher state changes.
Should an implementation not send half-RTT data, it may defer switching
traffic keys until both Finished messages have been exchanged. This will
not work well, as alerts sent in response to a bad client certificate
will be unreadable. The outgoing traffic keys must be switched early.
> Clarify that the key changes immediately at Finished.

- draft-ietf-tls-tls13.md
In TLS 1.2, empty tickets were used for the server to change its mind
about sending a ticket after committing to it in ServerHello:
> If the server determines that it does not want to include a
> ticket after it has included the SessionTicket extension in the
> ServerHello, then it sends a zero-length ticket in the
> NewSessionTicket handshake message.
This is not useful in TLS 1.3 where a server could decline to send a
ticket at all, so don't allow 0. (Fields tend to specify whether empty
values are allowed.)
Also lower the minimum NewSessionTicket.extensions size from 2 to 0.
Since we haven't defined any TicketExtensionTypes at all, it probably
should be allowed to be empty.
> Tweak NewSessionTicket lower bounds.

- draft-ietf-tls-tls13.md
There may be messages between ClientHello and ServerHello
(HelloRetryRequest and the second ClientHello), so use ... rather than
+.
> Fix typo in key schedule.

- draft-ietf-tls-tls13.md
Instead, talk about not rolling your own PRNG.  This document is
not the place to discuss how to do so, and RFC 40986 is a fine reference.
> Don't talk about rolling your own PRNG

- draft-ietf-tls-tls13.md
Outdent "Make Forward security after key change." paragraph.
> Formatting fix: section D.2

- draft-ietf-tls-tls13.md
No sender could possibly need to send half of a message interleaved with
application data in TLS, so forbid this. This cuts down on the
state-space a receiver needs to worry about.
This also means one cannot force the peer to buffer all but one byte of
a giant post-handshake message, and then never complete it for the
lifetime of the connection. (Although it does not remove all
steady state buffering DoS-type concerns.)
> Forbid post-handshake handshake/application interleave.

- draft-ietf-tls-tls13.md
We have a registry called "supported groups", and the extension is
"supported groups"; but each element is called a "named group" and the
data passed in the extension is a "named group list".  be consistent
in our terminology.
> extension name is "Supported Groups", not "Named Group"

- draft-ietf-tls-tls13.md
Noticed these while reviewing the negotiation PR:
---
handshake_failure means "the sender was unable to negotiate an
acceptable set of security parameters given the options available", but
these are all protocol errors that should only occur with a buggy
server. Switch them to more appropriate ones:
- If the HelloRetryRequest makes no sense, it is an illegal_parameter.
- If we get a second HelloRetryRequest, it's an unexpected_message (the
client is in a state where it expects a ServerHello and will likely
just fall through to the generic message-mismatch codepath).
- If HelloRetryRequest and ServerHello are inconsistent, it is an
illegal_parameter.
- If an anonymous server sends a CertificateRequest, it's an
unexpected_message (this too will likely use the generic
message-mismatch …
> Tidy up some client-sent handshake_failure alerts.

- draft-ietf-tls-tls13.md
From the past three times we've bumped the version, reality has
unequivocally told us that the TLS version negotiation, as described in
previous specifications, has been a collossal failure.
The working group decided not to replace the mechanism with a more
sustainable one, so do the next best thing in trying to save TLS from
itself. If the fields are renamed to what they actually are
('server_version' is the true version and 'client_version' is a
maximum), then perhaps we'll have some hope of future implementors
getting it right, if we ever clear through the prior iterations of the
bug.
While I'm here, remove the mention of 'The protocol version the current
record is compatible with' for record_version. record_version is purely
vestigial.
> Rename various version fields.

- draft-ietf-tls-tls13.md
It's only useful during the handshake, so avoid forcing the client save
that field for the in-handshake version.
> Require the CertificateRequest context to be empty in the handshake.

- draft-ietf-tls-tls13.md
The document was pretty crisp about the version downgrade protections, but
was less good about the changes to signature schemes.  I have made a few
changes to the description of signature_algorithms that should improve that.
In particular, I have made it clear that the RSASSA-PSS codepoints are also
defined for TLS 1.2 and that they can be used there.  That means that TLS
1.3 implementations need to be prepared to accept PSS signatures.
This also adds a section that points to the pieces that 1.2 implementations
need to consider.
> Improve the guidance around supporting TLS 1.2

- draft-ietf-tls-tls13.md
I think that this was just an error.  `status_request` is mentioned elsewhere in the text and seemingly permitted.
> status_request is Encrypted

- draft-ietf-tls-tls13.md
> Fix typo in cipher suite naming convention.

- draft-ietf-tls-tls13.md
> Swap in "e.g." for "for example".

- draft-ietf-tls-tls13.md
The PskKeMode and PskAuthMode types were not defined, substitute them by
the defined enums. Use non-plural enum names for consistency with other
enumeration types.
Remove the old opaque psk_identity type in favor of PskIdentity which
was otherwise unused. Increase minimum length from 2 to 4 to account for
the PskIdentity.identity field length.
> Fis PSK-related types

- mk-appendix.py
I also verified that the output for Python 2 and Python 3 are the same.
> Allow mk-appendix.py to run on Python 3 system

- draft-ietf-tls-tls13.md
At least to me, the KE phase description currently reads like the DH share and PSK are always sent.  It's DH, PSK, or both.
> Fixing KE Phase description.

- draft-ietf-tls-tls13.md
ClientHello mentions that early_data should be removed, but early_data doesn't mention it.  Editorial.
> Mention HRR in early_data extension definition

- draft-ietf-tls-tls13.md
I took this bit out of the 1st paragraph:
-If any of these parameters has no overlap between the
-client and server parameters, then the handshake
-will fail.
and moved it to the last para in the section because it doesn't say what alert value is to be returned, there's not something similar in the following paragraph that describes the PSK failure case, and finally the full failure text is included in the final paragraph.  Basically, I just move the failure case to the final paragraph.
An alternate would be to copy the failure to the PSK paragraph and include the which alert to return in the non-PSK para.
> Some tweaks for s4.1.1.

- draft-ietf-tls-tls13.md
It has been replaced by SignatureScheme which assumes that no more
HashAlgorithms will ever be allocated. Future allocations will go in
SignatureScheme.
Closes issue #574.
> Lock down the HashAlgorithm registry.

- draft-ietf-tls-tls13.md
No context and empty context are now declared to be the same. Add some
ALL CAPS WORDS for future specifications to deprecate no context. I used
SHOULD to forbid no context because, if some protocol currently uses no
context, switching it to empty context is a breaking change and probably
not worth it. We just want new ones to always provide a context.
This affects the rules for using exporters, so RFC 5705 is added to the
list of updated documents.
Closes issue #546.
> Clarify the behavior of no exporter context.

- draft-ietf-tls-tls13.md
The client and server versions have a different format.
> Clarify signature_algorithms extension.

- draft-ietf-tls-tls13.md
It looks like this is carried over from TLS 1.2---seems I was wrong and
TLS 1.2 did actually say whether there were leading zeros in front of
DHE parameters---but I believe it is no longer used.
Instead our crypto primitives all act on byte strings. Any conversion
between byte strings and the primitive's internal structures is handled
by the primitive itself. (RFC 7748 natively acts on byte strings,
4.2.4.1 specifies how FFDHE is encoded, RSA-PSS comes with a byte string
form, etc.)
> Remove note about representing integers as opaque vectors.

- draft-ietf-tls-tls13.md
the renegotiation mechanism from TLSv1.2 and earlier is
deprecated, that deprecation extends to the ability to
renegotiate existing TLSv1.2 (or earlier) session to TLSv1.3
> prohibit use of renegotiation to negotiate TLSv1.3

- draft-ietf-tls-tls13.md
since server hello says that presence of extra extensions is
a illegal_parameter and encrypted extensions say that presence
of server hello specific extensions is illegal_parameter
there is no reason to specify what to do with situation that
MUST generate fatal alert
> don't specify what to do if there are duplicated extensions

- draft-ietf-tls-tls13.md
According to the Section 3.5. Enumerateds there must be a comma before the
width definition (I found this mistake by writing an source-to-source compiler
for the presentation language).
> Editorial: Fix syntax errors

- draft-ietf-tls-tls13.md
TLS still permits shared point negotiation via ECDH, TLS 1.3 removes point _format_ negotiation.
> Clarify point format vs point negotiation removal.

- draft-ietf-tls-tls13.md
The select statement in Handshake should be based on Handshake.msg_type since the field is already defined and the select statement is unnamed and does not define its own field.
> Editorial: Select on Handshake.msg_type

- draft-ietf-tls-tls13.md
Each value in NamedGroup enum has 2 bytes. So the lower limit for named_group_list should be 2. Similar as [Errata 4633](https://www.rfc-editor.org/errata_search.php?eid=4633).
> Fix error in NamedGroupList

- draft-ietf-tls-tls13.md
We are inconsistent about "AEAD cipher" and "AEAD algorithm". RFC 5116
uses "AEAD algorithm" and "AEAD cipher" is confusing with "cipher
suite", so standardize on algorithm.
IANA considerations were never updated to actually add the cipher
suites. Fix that. Match the cipher suite name column with the IANA name
so we can reuse the table.
Finally, since we are defining new cipher suites, we should take care to
cite where our AEADs come from. Do so.
> Tidy up the text around AEADs and ciphers.

- draft-ietf-tls-tls13.md
This seems to have just been a mistake? Unlike ALPN, server_name isn't a
value that is selected by the server, so there's no need to match it
against a value stored in the session.
There is the issue of whether sessions are resumable across names or
other application-level contexts (for instance, whether we send client
certificates, different cipher profiles, etc.), but that is a more
complex issue than simply matching on server_name on the server side.
Moreover, any rules there would want to apply to resumption as a whole.
It seems there's no reason to have 0-RTT-specific rules over resumption
ones here.
> Remove server_name from the 0-RTT section.

- draft-ietf-tls-tls13.md
There is no alert for a server which requested a client certificate,
required it, but was not sent one. Servers today send a generic
handshake_failure which means clients must use heuristics to show error
messages to the user.
Unlike nearly every other negotiation in TLS, client certificate
selection is actually sometimes a user-level decision, so it is arguably
the most important place for us to have a dedicated alert.
(Also remove a "This alert is always fatal" note on
bad_certificate_status_response. All alerts are now fatal, so this is
redundant.)
> Add certificate_required alert.

- draft-ietf-tls-tls13.md
Avoid both starting with an existing hash AND ending with an existing
SignatureAlgorithm. In principle, this should not be necessary, but TLS
1.2 says:
>   signature
>      This field indicates the signature algorithm that may be used.
>      The values indicate anonymous signatures, RSASSA-PKCS1-v1_5
>      [PKCS1] and DSA [DSS], and ECDSA [ECDSA], respectively.  The
>      "anonymous" value is meaningless in this context but used in
>      Section 7.4.3.  It MUST NOT appear in this extension.
Bouncy Castle appears to have been enforcing this, causing interop
issues. As this was a straight-up MUST NOT, it seems prudent to
renumber. And if we're renumbering anyway, may as well avoid all the old
SignatureAlgorithms and avoid confusing tools like Wireshark.
> Renumber new SignatureSchemes.

- draft-ietf-tls-tls13.md
Right now it's under 'Cipher Suites' which is weird with the cipher
suite split. Backwards compatibility seems a better place for it since
we're talking about features in older versions of TLS that are now gone.
> Move 'Unauthenticated Operation' to backwards compatibility section.

- draft-ietf-tls-tls13.md
The text already says that both supported_groups and key_shares are in
order of "client preference". Supposing "client preference" is a
well-defined notion, we are already requiring the order match.
The SHOULD was also unclear on whether the list may be a general
subsequence. Clarify that this is allowed. This may be useful if, say,
we define some very large NamedGroup (post-quantum?) in the future that
is still preferable over the existing options. Clients would likely wish
to NOT offer it initially because it would be a waste of bandwidth for
the vast majority of servers which don't support it. (Not to mention
intolerance problems.)
In that scenario, a client would likely not predict a key_share by
default and instead use some kind of server info cache (either caching
what the server …
> Tighten and clarify KeyShareEntry ordering.

- draft-ietf-tls-tls13.md
MUST by generated independently -> MUST be generated independently
> Fix typo in Key Share section

- draft-ietf-tls-tls13.md
In the first paragraph, remove "that selects cryptographic parameters that don’t match the client’s 'key_share' extension".
Reason: According to section 4.2.5, HelloRetryRequest might not include the “key_share” extension. Also there is a whole section for Hello Retry Request. So I don't think we need to explain what a HelloRetryRequest is here.
> Editorial update for Client Hello section

- draft-ietf-tls-tls13.md
PR #641 changed enum values which would need updating by any experimental implementations that were actually using them. Even if this doesn't come up in practice, it should be listed in the changelog.
> update changelog for PR #641

- draft-ietf-tls-tls13.md
Other extensions are allowed to be empty. We may end up needing to
merely store an indicator someday.
> Allow empty TicketExtensions.

- draft-ietf-tls-tls13.md
> fixing indentation spaces.

- draft-ietf-tls-tls13.md
Criteria for one member structure / non structure is as follows:
Non structure: basic type -- not messages nor extensions
One member structure: others such as messages or extensions
> Fixing #627

- draft-ietf-tls-tls13.md
The spec requires that a cookie (or key_share) be present in HRR, but it's possible to send an empty cookie.  That's just inviting errors.
> Make a cookie have a minimum size

- draft-ietf-tls-tls13.md
I wanted to clarify in what part of the exchange the certificate_request_context field has a zero length.
> Clarification for the certificate_request_context definition

- draft-ietf-tls-tls13.md
This change adds a set of extensions to the Certificate message. This is
intended to hold all extension messages that are certificate-specific
as opposed to extensions that apply to the entire connection. This
change facilitates future extensions to the protocol for post-handshake
server authentication and resolves the anomaly of OCSP messages
appearing before certificates in the handshake.
> Move OCSP and SCT into Certificate message

- draft-ietf-tls-tls13.md
Various changes to make exporters/resumption work better. The rationale is to be able to do stuff in 0/0.5RTT.
- Add a 0-RTT exporter and change the transcript for the regular exporter (*).
- Explicitly allow predicting ClientFinished for NST when not doing
Client auth.
> Early ems2

- draft-ietf-tls-tls13.md
I am proposing that a client can also use the Zero-RTT with PSK-based authentication without having to rely on a previously obtained ticket.
> Allowing Zero-RTT with PSK

- draft-ietf-tls-tls13.md
RFC0793, RFC1948, RFC4302, RFC4303 and RFC5763 are not referenced by any text in the body of the current draft. So remove them from the reference section.
> Remove unused references

- draft-ietf-tls-tls13.md
I went through and did a check of our current references usage. There's quite a few that need to be cleaned up. The 7 normative refs this PR drops are for cipher suites that are no longer applicable to TLS 1.3 in the new negotiation. (for the replaced ones, we cite the algorithm RFC rather than the cipher RFC, now) There's also 5 informative refs we just don't cite anymore.
Beyond those currently in this changeset, we also have the GCM, PKCS6, & PKCS7 refs which are currently unused as well. Not sure if we want to drop them too or stick them in where appropriate now.
> drop unused references

- draft-ietf-tls-tls13.md
832b864f78784b7d06e300148c478877a4398d6e introduced this syntax error.
> fixing the mismatch of ASN1Cert and ASN1CertData.

- draft-ietf-tls-tls13.md
with few possible exceptions, enumerateds will assume values
different than the ones they were originally defined with.
Backwards compatibility of Client Hello is dependent on
implementations being able to ignore values they do not
know about.
> don't specify that enumerateds can assume only specified values

- draft-ietf-tls-tls13.md
Before record protection is established, if an endpoint receives a TLSPlaintext structure whose "length" field is too large (>2^14), should it send a "record_overflow" alert?
> Clarify what to do when TLSPlaintext.length is too large

- draft-ietf-tls-tls13.md
The MTI Extensions section is currently out-of-date. It wasn't updated with the new negotiation and still refers to the old cipher suites system. This PR cleans that up.
I also drop the cookie extension universal send requirement, as that was in there as an alternative to allowing a server to send a cookie without first being prompted. We have that in as an explicit exception, currently.
> update MTI Extensions section for new negotiation

- draft-ietf-tls-tls13.md
All other fields deprecated by this spec use "MUST be set to ...", such as ClientHello.legacy_version, ClientHello.legacy_compression_methods, TLSPlaintext.legacy_record_version. Only ClientHello.legacy_session_id "SHOULD be set as [...]" So I suggest changing this to "MUST" as well.
> legacy_session_id: SHOULD -> MUST

- CONTRIBUTING.md
- README.md
It seems https://trac.tools.ietf.org/wg/tls/trac/wiki is no longer in use. Can we change the link to https://datatracker.ietf.org/wg/tls/documents/?
> [README.md] Update home page link

- draft-ietf-tls-tls13.md
RFC 5226 obsoleted RFC 2434 so we should refer to that to avoid a GENART review comment.
> Refer to RFC 5226

- draft-ietf-tls-tls13.md
1) Switches uses of ALPN label/value to "ALPN protocol" (to clarify this is referring to a single protocol, not the entire extension)
2) Remove plural from external PSK case (if there's not way for the client to select which protocol the 0-RTT data uses, it doesn't make sense for there to be multiple options)
3) Switch reference from RFC7443 to RFC7301 (I assume this is what was intended)
I think this makes the intended behavior of the spec a bit more clear.
> Clarify ALPN with 0-RTT (existing behavior).

- draft-ietf-tls-tls13.md
This patch clarifies the presentation language to fix issue 700.
> Explicitly saying that a case can have multiple fields. (#700)

- draft-ietf-tls-tls13.md
- The caveats at the beginning are silly
- We don't seem to every use  Foo = { A, B} but we do use Foo = A;
> Revise syntax description

- draft-ietf-tls-tls13.md
We don't actually use this syntax, and having it in here just adds useless complexity. Defining syntax we don't actually use just risks confusing people reading the document for the first time.
> drop unnecessary definition of valueless enums

- draft-ietf-tls-tls13.md
Variants is not a subsection of Constants; just have them all be subsections of same depth within Presentation Language
https://tools.ietf.org/html/draft-ietf-tls-tls13-17#section-3.7
> fix Presentation Language sectioning

- draft-ietf-tls-tls13.md
TLS 1.3 only has a handful of cipher suites, and no low security ones. This text is obsolete, so this PR removes it and bumps the certificate part of this small section up to the previous section on certificates.
> drop old text about old low security cipher suites

- draft-ietf-tls-tls13.md
I think this aside is out-of-date: extensions cannot be empty, and there are now defined extensions to put here.
> Remove out-of-date note about helloretry extensions

- draft-ietf-tls-tls13.md
Adding "itself" makes the sentence much easier to understand.
Actually, two Japanese, who are implementing TLS 1.3 independently,
took a long time to understand this.
> clarifying that the server authenticate *itself*.

- draft-ietf-tls-tls13.md
I noticed that some of the arrows were off, so I did a quick check on the others. This fixes:
* arrows in the key schedule chart aren't all the same length
* an arrow in resumption isn't lined up with the others
* a few charts have arrows a couple characters off-center (this just aligns all these arrows to start at char 34)
* one instance of a right column message not fully right-aligned ("[Application Data]" in HRR)
> fix arrows to be positioned/sized consistently

- draft-ietf-tls-tls13.md
Fix a reference to a section that's directly citing a section number in plain text. (not linkified and will break if sections change) I assume this is a copy/paste error.
> fix section reference

- README.md
I overlooked this link in #698. Let's change the link in the top section to https://datatracker.ietf.org/wg/tls/documents/ as well.
> [README.md] Update WG link

- draft-ietf-tls-tls13.md
The prefix to the label in HKDF-Expand-Label is 9 octets long.
The grammar therefore permits the label to be empty.  That would
be bad given that it is supposed to disambiguate.
(Yes, a zero length string is potentially unique, but since only
one of them exists and use is more likely the result of an error
than intent, it seems prudent to forbid its use.)
> Set minimum label size in HKDF-Expand-Label to 10 octets

- draft-ietf-tls-tls13.md
Fix incorrect suggestion that `ticket_age_add` of NST affects `early_data` extension.
> obfuscated_ticket_age is part of the PSK extension

- draft-ietf-tls-tls13.md
It could be just me, but the previous wording was kind of confusing (YMMV).
> Slightly improve wording and fix typo in CertificateVerify section

- draft-ietf-tls-tls13.md
"Clients" is plural, so "It" doesn't make sense here.
> Clarify subject in one sentence

- draft-ietf-tls-tls13.md
TLS 1.3 uses new cipher suites; there's no longer any overlap. Updating this line to carry the same meaning it had before the new negotiation was introduced.
> update backwards compatible suites language

- draft-ietf-tls-tls13.md
1. TLSCiphertext.fragment is undefined. I guess it should be "TLSCiphertext.encrypted_record"?
2. This sentence "due to the inclusion of TLSPlaintext.type and however much padding is supplied by the sender" is unclear to me. Does it mean "due to the inclusion of TLSPlaintext.type and the padding"?
> Fix typo in Section 5.2

- draft-ietf-tls-tls13.md
When I was implementing the key schedule, it was unclear to me what `Hash(Messages)` stands for. This additional note would help other implementors. 
Kazuho Oku pointed out the similarity to Handshake Context. So, I updated that part, too.
> Clarifying the concatenation rule

- draft-ietf-tls-tls13.md
This would help to understand what extensions should be encrypted.
> Encrypted extension refers to the table in IANA consideration.

- draft-ietf-tls-tls13.md
The handshake context here is just the transcript of the handshake messages, not the hash of the transcript. The language makes it seem like the authentication messages are Hash(Hash(handshake messages) + Certificate), etc.
> Clarify authentication message language.

- draft-ietf-tls-tls13.md
The alert is described as being part of the first flight, but it is
really sent when the server Finished is received, per the processing
order section. Notably, servers MUST NOT wait for end_of_early_data
before sending ServerHello through Finished. Group it with the client
Finished flight, and fix the text about it terminating the first flight.
(The division between the first and second client flight isn't
especially well-defined because early data may flow in parallel with the
ServerHello flight. But if there is to be a division, end_of_early_data
certainly falls into the second one.)
> Align end_of_early_data text and diagram with processing order.

- draft-ietf-tls-tls13.md
HashValue is confusing because this argument is not
always a hash value. For instance, "" is used sometime.
> Using Value instead of HashValue.

- draft-ietf-tls-tls13.md
Ticket is a term that refers to a PSK identity established using an handshake. For out-of-band PSK, we do not use the term.
> change "external ticket" to "identities established externally"

- draft-ietf-tls-tls13.md
extension, as suggested by Steven Valdez/David Benjamin.
> Consolidate ticket_early_data_info and early_data into a single

- draft-ietf-tls-tls13.md
Most of these are simple enough, kramdown treats all bracketed text as a reference.  So these can be replaced with `\[` and the warnings go away.  The biggest change here is slightly stylistic: a few places had `[{{server-hello}}]`, which kramdown complained about, but rendered correctly.  However, this produced a non-sentence.
Also, I fixed some inconsistent use of references and s/data/date in one of the references.
> Quiesce build warnings

- draft-ietf-tls-tls13.md
This is just to make things a little more consistent. All but a handful
of labels are vertically aligned. Two of the arrowheads were two spaces
away from their target rather than one. One of the labels was two spaces
away from the edge rather than one.
> Artistic tweaks to the state machine drawings.

- draft-ietf-tls-tls13.md
Exporters and (EC)DHE secrets are not traffic secrets. Group the two
(EC)DHE sections under a name which matches what the key schedule
section calls it (the "(EC)DHE shared secret") and link to it from the
key schedule.
> Tweak sectioning in Cryptographic Computations.

- draft-ietf-tls-tls13.md
The other line-breaked expressions in the document do not use quite so
many newlines. I believe this matches the existing style, based on how
Derive-Secret is defined.
> Use fewer newlines in verify_data expression.

- draft-ietf-tls-tls13.md
This is a redo of PR #643 now that PR #678 has removed the appending
rule and resolved issue #644.
> (Re-)tighten and clarify KeyShareEntry ordering

- draft-ietf-tls-tls13.md
This advice is about RSASSA-PKCS1-v1_5 which is no longer applicable.
(The note to accept both NULL and missing parameters was also wrong in
TLS 1.2 and encourages using an actual ASN.1 parser, a dangerous
implementation strategy for RSASSA-PKCS1-v1_5. RFC 3447 section 8.2.2
says verification must compute the serialized EM' and compare EM against
it, which implies one and only one padded DigestInfo serialization is
valid.)
> Remove outdated implementation pitfall about RSA padding.

- draft-ietf-tls-tls13.md
This is a giant pile of nitpicks, loosely inspired by the FFDHE alert
discussion.
The old text specifies a handshake_failure which is redundant with and
contradicts the Cryptographic Negotiation section. The old text says
only handshake_failure is allowed while Cryptographic Negotiation allows
both handshake_failure and insufficient_security. Fix this by avoiding
redundancy as the failure cases are global to the overall negotiation
algorithm.
Next, align the tense with itself and the rest of the text. Most of the
text appears to be written in present tense. The old text for SH said:
The server *will send* [...] when it *was* able to [...]
which is a little odd. Also align the wording between the two. Talk
about a server (singular) to match Cryptographic Negotiation and say
"parameters" …
> Various ServerHello and HelloRetryRequest nitpicks.

- draft-ietf-tls-tls13.md
Reading through the spec again I found a few tiny things to fix. I'm suggesting to replace "Zero-RTT" with "0-RTT" in the paragraph because I found "Zero-RTT" used only in headlines, but "0-RTT" consistently in paragraphs.
> Fix things, add things, use 0-RTT in paragraphs for consistency

- draft-ietf-tls-tls13.md
The client should be required to verify the CertificateVerify message. In addition I prefer to specify the alert type in case the verification fails (also for the Finished).
> Certificate verify

- draft-ietf-tls-tls13.md
Per the recent thread. I could have sworn this was in here, but can't
find it...
The NewSessionTicket section explicitly says to ignore unknown
extensions, so I've added the analogous text to ClientHello and
CertificateRequest.
> Clarify when unrecognized extensions are ignored.

- draft-ietf-tls-tls13.md
Added note in security properties section on the fact that the client cannot determine if the server considers the connection to be mutually authenticated.
This paragraph condenses the main takeaway from the discussion at
https://www.ietf.org/mail-archive/web/tls/current/msg22382.html
Cas Cremers, Marko Horvat, J. Hoyland, T. van der Merwe, and Sam Scott.
> Security properties: note on awareness of authentication status

- draft-ietf-tls-tls13.md
I wonder why this was only a `SHOULD` before.
Am I right to assume that this is because TLS 1.3 has removed support for static DH and leaking an ephemeral key is not considered to be a security problem?
> DH params: Peers MUST validate each other's public key

- draft-ietf-tls-tls13.md
I guess this was removed by accident in https://github.com/tlswg/tls13-spec/commit/cbc261a864236fe1424ac3a9826a7833e164a218
> Specify _which_ servers should set the random value's suffix

- draft-ietf-tls-tls13.md
To fix #861, let's add semi-colons to EarlyDataIndication. To make the presentation language simpler, let's remove fall-through which is not used in other places.
> No fallthrough

- draft-ietf-tls-tls13.md
The structure of exporters is not conducive to forward security when there are multiple types of exporters in use.  This PR proposes to add an extra `Derive-Secret` stage to the derivation of exporters.  
An endpoint could support multiple uses of exporters against the same connection.  If the implementation wants to export multiple values over time with multiple exporter contexts, it has to retain the exporter secret.  The existence of that exporter secret is a risk to any other keys that are exported from the connection.
An endpoint might know the potential *types* of exporter that it could use, but it won't always know all of the contexts that it might have to use.  Thus, it needs to retain the exporter secret as long as it might need to use it.
In quicwg/base-drafts#25 you can see an …
> Add an additional Derive-Secret to exporters

- draft-ietf-tls-tls13.md
benefits:
(1) Restoring extract/expand parity, thus cleaning up the theoretical
treatment wrt HKDF and future replacements.
(2) Futureproofing against someone being able to force the ECDHE
value in the second HKDF-Extract to collide with one of the labels.
This seems unlikely with current groups, but might be possible
with some future algorithm. (Issue due to Trevor Perrin).
> Add an extra Derive-Secret stage prior to HKDF-Extract. This has two

- draft-ietf-tls-tls13.md
An EndOfEarlyData message signals a key change. A ClientHello can be the
last message read before a key is changed, and it never makes sense for a
ClientHello to have more data after it in the record.
> End of ClientHello and EndOfEarlyData messages should be on a record boundary

- draft-ietf-tls-tls13.md
server to just store H(CH1) when doing HRR.
@davidben PTAL
> Special-case the hash for CH1 when HRR is used. This allows the

- draft-ietf-tls-tls13.md
client to implement because it knows what hash the server will
select. Also clarify the language about HRR and Key Shares.
> Add cipher suite to the HRR. This makes it slightly easier for the

- draft-ietf-tls-tls13.md
31f836238e5968a85c9e4d64d8ab23c0bbed8061 missed a spot.
> Suggest more strongly that EndOfEarlyData is deferred.

- draft-ietf-tls-tls13.md
1. Move the list to the new transcript hash section.
2. Note that EndOfEarlyData goes in the client Handshake Context.
> Clean up description of messages in the transcript hash:

- draft-ietf-tls-tls13.md
This tweaks some text in ClientHello with regard to handling the extensions field. The two blocks of text on it in this section are merged together, dropping a little repeated information and putting it in one paragraph after definition of the relevant field instead of covering this in two places in the same section.
> extensions cleanups in ClientHello

- draft-ietf-tls-tls13.md
- Explicitly define RFC 7250 certificate support.
> - Remove support for disallowed extensions (cert_type, user_mapping).

- draft-ietf-tls-tls13.md
Need to be explicit say that it's the ExtensionType registry from RFC 4366.
> IANA considerations section tweak.

- draft-ietf-tls-tls13.md
I removed some of the references that IDnits reports as unused.
@ekr Can we delete the AES and GCM references they're really picked up by the cipher suite referenes? We'll need to refer whatever RFC5289 @ PS ends up being for the AES_GCM suites.
> IDNits reports unused references.

- draft-ietf-tls-tls13.md
Make the variable names of various secrets correspond to the
labels used for Derive-Secret(). This is not a wire format
change, but just a change in the internal variable names.
> Update variable names. Fixes #942.

- draft-ietf-tls-tls13.md
be unpredictable in order to prevent pre-computation of
CertificateVerify. Maybe this should actually be a MUST?
> Require (2119 SHOULD) that the certificate context for post-handshake

- draft-ietf-tls-tls13.md
When we banned client auth and PSK, we only meant to do it for
the main handshake, not the post-handshake phase. This reverts
that change, as well as clarifies the prophibition on PSK plus
cert-based auth.
> Re-enable post-handshake client authentication for PSK handshakes.

- draft-ietf-tls-tls13.md
Per mailing list discussion, this allows us to have every HKDF-Expand just
have one hash block of info.
@ilaril would love your feedback.
> Shorter HKDF labels. Fixes #964.

- draft-ietf-tls-tls13.md
RFC 7301 defines the ALPN extension and defined a new alert "no_application_protocol". TLS 1.3 uses ALPN but currently misses the alert in Section 6.
> Adding missing "no_application_protocol" alert

- draft-ietf-tls-tls13.md
Resolves #984.
Note that I'm not entirely convinced we need the GCM reference because RFC 5116, which is referenced in B.4 for the suites, includes a reference to it.
> removing unused references

- draft-ietf-tls-tls13.md
make submit returned this error:
- No link definition for link ID 'rfc 5869' found on line 6144
so I removed the space.
> fixing spacing in 5869 reference

- draft-ietf-tls-tls13.md
> fixing syntax errors of ID 20.

- draft-ietf-tls-tls13.md
Even when (EC)DHE is in use, the "supported_groups" extension is
only mandatory in the ClientHello; it can be omitted from the
EncryptedExtensions, as per section 4.2.6.
Given that, it is not MTI for the server sending to the client, but
the client must be prepared to accept the extension in EncryptedExtensions
(at least to the point of not crashing or aborting the handshake), so
leave the MTI text unchanged.  It would be too awkward to try to
express this subtlety in such a concise list.
> "supported_groups" is not MTU in EncryptedExtensions

- draft-ietf-tls-tls13.md
HKDF-Expand-Label has changed between draft -19 and -20, clarify that
"HDF Hash" refers to the hash algorithm and not a version-specific
instance of HKDF-Expand-Label which is populated with a hash algorithm.
> Clarify "KDF Hash"

- draft-ietf-tls-tls13.md
The 0-RTT key might differ between TLS versions (as demonstrated with
the draft -20 changes). Be explicit about storing this version number
since section 4.2.9 requires this information too.
> PSK context for 0-RTT needs version number

- draft-ietf-tls-tls13.md
Follow up to PR #981. Add a link for the ALPN RFC to the relevant alert's description. (same as with other extension alerts above)
> cite RFC for alert

- draft-ietf-tls-tls13.md
There are a number of different alerts that may be suitable for sending
to indicate a non-acceptable cert chain, e.g. certificate_revoked,
certificate_expired, unknown_ca, etc. We should not restrict the client
to only sending one specific alert.
> Allow clients to use any suitable alert if a non-acceptable cert chain

- draft-ietf-tls-tls13.md
Very trivial comment fix. Just makes the indentation & capitalization of a comment match the others near it.
> trivial comment fix

- draft-ietf-tls-tls13.md
ticket is associated with a different PSK. This provides somewhat
increased security in cases where you have multiple PSKs for the
same connection and one PSK is compromised.
The motivation here is that in cases where the server maintains a
session database rather than self-encrypted tickets, the server might
delete tickets as they are used,. This change provides FS for
connections which have been used, even if there are other outstanding
tickets in the session cache associated with the same original
connection.
> Add a new derivation stage for PSKs off of the RMS so that each session

- draft-ietf-tls-tls13.md
This was the one extension that wasn't in the extensions section, which made it hard to find.
Note I've also removed the indent on the trailing paragraphs to avoid the walloftext problem with the existing text.
> Move OID Filters extension

- draft-ietf-tls-tls13.md
> trusted_ca_keys became certificate_authorities; catch up

- draft-ietf-tls-tls13.md
As discussed, an empty value should be fine.
> Allow an empty ticket_nonce

- draft-ietf-tls-tls13.md
> fixing a typo.

- draft-ietf-tls-tls13.md
This is no longer a hash value throughout, using a different name might reduce confusion a little.
> Rename HashValue to Context for HKDF-Expand-Label

- draft-ietf-tls-tls13.md
All of the other `select`s (including in the description of the presentation) have a space between the `select` and the `(`.
> Space after `select`

- draft-ietf-tls-tls13.md
Now `uint16 ProtocolVersion;` is defined by the presentation language.
> Specify type aliases.

- draft-ietf-tls-tls13.md
Fix the spacing in `UncompressedPointRepresentation` and add it to
Appendix B.3.1.
Add missing space in `select (...){`.
> Normalize spacing and add missing struct to B.3.1

- draft-ietf-tls-tls13.md
The presentation language only specifies `/* ... */` as a comment. It
doesn't really apply to the `Transcript-Hash`, but it seems good to be
consistent.
> Use /* comments */ rather than //

- draft-ietf-tls-tls13.md
Including the first name of the author in "ins" causes xml2rfc to produce junk.
> Fix reference

- draft-ietf-tls-tls13.md
This change rephrases the requirements and recommendations from
prescribing specific mechanisms of 0-RTT replay protection to
prescribing the guarantees expected from implementations, thus letting
the implementations to choose the way they can provide those guarantees.
This change also introduces a MUST-level requirement for protection
equivalent to having at least local strike register.
> Rephrase and tighten the 0-RTT replay protection requirements

- draft-ietf-tls-tls13.md
The padding extension is typically computed as part of serializing the
ClientHello, in hopes of targetting a particular size. As specified right now,
the second ClientHello must not use this same logic and instead must retain the
previous extension sizethough this would likely not hit the same target size.
The server's going to ignore it anyway, so allow it to be recalcuated. This
avoids unnecessary state in clients and extra logic to serialize the first and
second ClientHellos differently.
> Allow the padding extension to change on HRR.

- draft-ietf-tls-tls13.md
As mentioned by @Andrei-Popov in
https://www.ietf.org/mail-archive/web/tls/current/msg24561.html .
> Document no NUL bytes in labels

- draft-ietf-tls-tls13.md
The TLSPlaintext size is at most 2^14, so the TLSInnerPlaintext must be
at least one more to fit the content type. This matches with the end of
the record payload protection section.
> Fix TLSInnerPlaintext limit

- draft-ietf-tls-tls13.md
Both for 0-RTT and 1-RTT.
Give NST- and externally-provisioned PSKs more uniform treatment.
Closes: #1040
Closes: #1043
> Be more explicit about PSK requirements

- draft-ietf-tls-tls13.md
Currently, the draft says that servers MAY send multiple tickets to clients without further discussion. It might help to be concrete and provide an example for when more than one ticket is useful. This PR provides one example.
> Add text explaining why servers might want to vend multiple tickets

- draft-ietf-tls-tls13.md
Minor change to where RFC 6066 is referenced.
> certificate_authorities is defined in this document, not in RFC 6066

- draft-ietf-tls-tls13.md
Currently TLS 1.3 specifies close_notify in the same way that TLS 1.2 did.
I believe that has issues and this might be the right time to fix them.
The purpose of close_notify is to protect against data truncation attacks,
each side is required to send close_notify before closing the write side of
the transport connection so the other side knows that the data was not truncated.
As such, close_notify only needs half-close semantics to prevent truncation.
However, the specification contains the following text:
<< Each party MUST send a “close_notify” alert before closing the write side
of the connection, unless some other fatal alert has been transmitted.
The other party MUST respond with a “close_notify” alert of its own and close
down the connection immediately, discarding any pending …
> Give close_notify half-close semantics to better match TCP and avoid truncation

- draft-ietf-tls-tls13.md
the RFC 7250 semantics that both certificate types are globally
negotiated. There is no support for mixed certificates.
> Move server_certificate_type to EE. The idea here is to retain

- draft-ietf-tls-tls13.md
There is no reason from cryptographical point of view to not resume
across multiple domains.  The primary concern comes from
interoperability concerns and potential waste of tickets, hence the
default should be to not resume.
> Allow resumption across multiple domains

- draft-ietf-tls-tls13.md
Give some motivation for why servers MAY send multiple tickets.
> Refer to client-tracking prevention from NST message

- draft-ietf-tls-tls13.md
This is mentioned throughout the document, but not in the "Mandatory-to-Implement" section.
closes #1104
> add messages that are required to have the supported_versions extension

- draft-ietf-tls-tls13.md
Without specifying the encoding, I don't think it's actually defined how
you transit the certificates. RFC 5280 only says that the TBSCertificate
is DER-encoded for computing the signature, which still allows insanity like XER-encoded everything
with the receiver re-encoding the TBSCertificate to DER before verifying
the signature.
> Clarify that X.509 certificates carried over TLS are DER-encoded.

- draft-ietf-tls-tls13.md
The peer must advertise extensions before they can be sent with a
certificate message.
Fixes #1111
> Clarify certificate extensions

- SUBMITTING.md
Command-line commands are now surrounded within code tags, which results in a nicer Markdown rendering.
> put commands between code tags

- draft-ietf-tls-tls13.md
8126 obsoleted 5226.  Saving us a GENART comment.
> update reference 5226->8126

- draft-ietf-tls-tls13.md
RFC 8174 updates RFC 2119 so the boilerplate words have changed slightly according to s2 of RFC 8174.  Just trying to save us another GENART comment.
> 8174 updated 2119

- draft-ietf-tls-tls13.md
- There are many sorts of TLS middleboxes (CDN, decrypting proxy, local
antivirus, actual attack, etc), with acceptabilities ranging from
reasonable to extremely questionable to a terrible idea.
(Categorization is left as an exercise to the reader.) They also have
very different security considerations.
Fundamentally, TLS secures a connection between two endpoints. As
such, we have something to say about the endpoint-to-endpoint
connections that make up such a system, but we shouldn't imply this
section is *sufficient*, merely *necessary*. Adjust the text
accordingly.
- I wrote "intermediary" in the original PR, predictively based on PR
#1115. Since the spec seems to have settled on "middlebox", align the
terminology. (I don't really care what is used, just that it is
consistent.)
> Tweak protocol invariants text a little.

- draft-ietf-tls-tls13.md
remove extra _ at the end of name -- the name in SignatureScheme
enum lacks it
> fix typo in constant name

- draft-ietf-tls-tls13.md
the type is called signature_algorithms_cert (singular) everywhere,
not signature_algorithms_certs (plural)
> fix signature_algorithms_cert typo

- draft-ietf-tls-tls13.md
46 was used but never assigned.
Let's add the same comment as 40.
> adding reserved.

- draft-ietf-tls-tls13.md
Issue 1: supported_versions is required in TLS 1.3 SH.
Issue 2: supported_versions.selected_version must be identical in HRR and SH
> Clarify rules around "supported_versions" extension in SH and HRR

- draft-ietf-tls-tls13.md
"A client MUST provide a 'psk_key_exchange_modes' extension
if it offers a 'pre_shared_key' extension."
> add psk_key_exchange_modes ext to MTI

- draft-ietf-tls-tls13.md
> dropping RFC4681 (user mapping) reference)

- draft-ietf-tls-tls13.md
`legacy_record_version` says:
> This value MUST be set to 0x0303 for all records generated by a TLS 1.3 implementation other than an initial ClientHello (i.e., one not generated after a HelloRetryRequest), where it *MAY* also be 0x0301 for compatibility purposes.
But the following text follows:
> n order to maximize backwards compatibility, records containing an initial ClientHello *MUST* have version 0x0301 and a record containing a second ClientHello or a ServerHello MUST have version 0x0303, reflecting TLS 1.0 and TLS 1.2
MAY and MUST mismatch. Let's s/MUST/SHOULD/
> using SHOULD intead of MUST for 0x0301 in CH1.

- draft-ietf-tls-tls13.md
The previous wording implied that a session in which an actor's key has been compromised should enjoy "peer authentication", which is defined just above to mean that both parties should authenticate each other. This adjusts the wording to make it clear what we intend, which is that compromising Alice's key should not allow you to impersonate Bob to Alice. (cc @cascremers)
> Adjust the wording around KCI attacks

- draft-ietf-tls-tls13.md
This clarifies two items relevant to stateless HelloRetryRequests:
1) If a HelloRetryRequest does not contain a key_share extension, the negotiated group does not have to match the non-existent selected group in the HRR.
2) If a HelloRetryRequest does select a group, the server can still choose to use psk_ke key exchange. When sending a stateless HelloRetryRequest, the server may not know if it will accept a PSK yet. This allows the server to still select a group in the HelloRetryRequest which it would need for a full handshake, but later decide to accept the PSK with psk_ke mode.
> Clarify requirements between key_share in HRR and SH.

- draft-ietf-tls-tls13.md
Given that it's common to select the strongest cipher by default
(thus likely using SHA-384 PRF) and that the default Hash associated
with a PSK is SHA-256, simple upgrade of server and client
to TLS 1.3 may cause handshake failures if only PSK key exchanges
were configured and the existing implementor's note is followed.
> legacy PSKs note

- draft-ietf-tls-tls13.md
Need to change the header to obsolete 6961 (as noted in the text).
> 6961 is obsoleted

- draft-ietf-tls-tls13.md
It appears we should have included rules for populating a registry for the psk_key_exchange_modes extension.
> adding TLS PskKeyExchangeMode Registry rules

- draft-ietf-tls-tls13.md
The I-D checklist requires that updates and obsoletes be included in the abstract; thought RFC.  I personally feel this is [redacted] stupid, but I do not think that we should risk a process appeal to fight this battle.
> Forced additions to the abstract

- draft-ietf-tls-tls13.md
ClientHello, etc., processing rules are in earlier versions too. We're just
calling out some corollaries of it all.
> Remove misleading clause.

- draft-ietf-tls-tls13.md
As naïve handling of external identities may cause the server to
be vulnerable to identity enumeration attacks, refer the section
that discusses that danger in the PSK section itself.
> reference the security section about external identities in PSK description

- draft-ietf-tls-rfc8446bis.md
Based on the PSK authentication was not included in the past. I think specification has some places where "Client Authentication" refer to only certificate-based client authentication and not client authentication is general.
Not a big thing, but I think it might confuse some readers, and would be good to clarify.
> Editorial: "Client Authentication" -> "Certificate-Based Client Authentication"

- draft-ietf-tls-rfc8446bis.md
In WG discussion of draft-vvv-tls-cross-sni-resumption-00, tracking
implications came up. While that draft does expand the set of servers
that can cross-resume, it's not a new issue. For instance, on the Web,
if https://a.example and https://b.example both include a subresource to
a common https://tracker.example, TLS session resumption may be used to
correlate activity across the two sites.
Add some text to discuss this. This is distinct from the single-use
ticket mitigation, which only covers correlation by passive observers.
Correlation by the server itself is pretty much inherent to session
resumption and other cache-like optimizations. Instead, the text points
this out and gives an example of how applications can keep their
resumption scopes consistent with their privacy goals.
Fixes …
> Discuss tracking implications of session resumption.

- draft-ietf-tls-rfc8446bis.md
As discussed on the TLS list. It seems like cipher suites without confidentiality is already registered. Feel free to reformulate in any way. Refering to the cipher suites in the document is not very useful for the reader, and it does not seem to be a rule that a NULL encryption could not be recommended even if that seems very unlikely.
I also suggest adding "(certificate)" after client identity. The security property does obviously not hold for PSK authentication.
> Security Property - Protection of endpoint identities

- draft-ietf-tls-rfc8446bis.md
Closes #1203. I wasn't sure where to put this text. There was an Appendix talking about TLS 1.2, so I figured it could go nearby. And then it probably wanted to go before that Appendix so there isn't ambiguity about how to refer to EMS.
> Align TLS 1.2 terminology with this document

- draft-ietf-tls-rfc8446bis.md
This attack is often possible even without a timing channel due to application-layer behaviors that allow cache probing (e.g. in HTTP and DNS).
This change addresses the original concern in #1225. A more thorough revamp of the anti-replay and side channel recommendations might be needed to address all the questions raised there.
> Reduce emphasis on timing in the 0-RTT cache attack

- draft-ietf-tls-rfc8446bis.md
MGF1 got unhelpfully spelled out as "mask generation function 1" in RFC 8446. I'm guessing this is the result of an acronym expansion editting pass, but the function is simply called "MGF1". There is no such thing as "mask generation function 1".
Correct this back to MGF1. In hopes this doesn't get hit the same editing pass later, I've tweaked the wording and moved the citation so that "mask generation function" is still uttered before MGF1, and it's clearer that both primitives are defined in RFC 8017.
> Fix reference to MGF1

- draft-ietf-tls-rfc8446bis.md
close_notify has always used a warning alert level, but this is not actually written down anywhere. It seems to have gotten lost as early as RFC 4346 (TLS 1.1!). In RFC 2246, there is some text that mentions the correct level is warning as an aside in describing something else.
>   close_notify
>       This message notifies the recipient that the sender will not send
>       any more messages on this connection. The session becomes
>       unresumable if any connection is terminated without proper
>       close_notify messages with level equal to warning.
I wasn't able to find any other text that discussed this. Then, RFC 4346 dropped the session termination behavior:
>   close_notify
>      This message notifies the recipient that the sender will not send
>      any more messages on this …
> Specify the alert level of close_notify.

- draft-ietf-tls-rfc8446bis.md
After the whole paragraph on forward secrecy and exfiltration was merged to Appendix F.1 I probably deserve to be included.
> Adding John Preuß Mattsson as contributor

- draft-ietf-tls-rfc8446bis.md
- FIPS 186-4 is obsolete
- Curve definitions have moved to the new NIST SP 800-186
- ANSI X9.62 is behind a paywall and should be avoided if possible. References behind paywall can not be accessed by most readers. This makes it harder to implement and to evaluate the security of the protocol. FIPS 186-5 removed the dependency on ANSI X9.62 and defines ECDSA itself. Point validation is defined in the new  NIST SP 800-186.
> FIPS.186-5 has been published by NIST

- draft-ietf-tls-rfc8446bis.md
but tell receiving implementations not to enforce them.
This addresses #1299. @martinthomson PTAL.
> Fixes #1299. Require key updates

- draft-ietf-tls-rfc8446bis.md
They denote optional components of the presentation language and are not literal components of the presentation language itself.
Fixes #1315
> Clarify that double brackets are not part of the presentation language

- draft-ietf-tls-rfc8446bis.md
This tries to make the situation clearer. It does add a normative SHOULD but I think it's obvious.
> Clarify how to negotiate groups if you want to respect the client order.

- draft-ietf-tls-rfc8446bis.md
So say that, alternative to #1335.
Closes #1335.
> not-same might be greater, this is less

- draft-ietf-tls-rfc8446bis.md
Based on Christian Huitema discussion of potential solutions.
https://mailarchive.ietf.org/arch/msg/tls/QuKsIu1gZFDfLn1x-ZnOE_LQxyc/
Encrypting the PSK identity using mechanisms external to TLS is missing in the current text. I added as little as possible. I did not go into details of the external encryption (could be asymmetric, symmetric group key, or pairwise symmetric with trial decryption).
> Privacy and PSK identifiers

- draft-ietf-tls-rfc8446bis.md
I see a dead link for the ref to the AEAD-LIMITS ref. I believe this is the same paper just without the date on the 1st page.
> AEAD-LIMITS ref

- draft-ietf-tls-rfc8446bis.md
Two entries were updated not one; also see https://www.rfc-editor.org/errata/eid5976.
> counting for IANA

- draft-ietf-tls-rfc8446bis.md
Knocking off another IDnit by including 8422 in the abstract; this I-D is updating it so it needs to be listed.
> Add 8422 to abstract

- draft-ietf-tls-rfc8446bis.md
RFC 7230 was obsoleted by 9112.  Not entirely sure we need to do this but it will get rid of one more IDnit.
> Update HTTP/1.1 ref

- draft-ietf-tls-rfc8446bis.md
I noticed this as I was looking for where we officially wrote down the implications of the X.509 Key Usage extension. We wrote it down for the server, but forgot to for the client.
The root issue is that we unified certificate negotiation in TLS 1.3 (ClientHello/Certificate and CertificateRequest/Certificate are now nice and symmetric), but forgot to correspondingly unify some of this prose. As a result, we said the same thing in different ways, and forgot different things in either place.
This change merges the two.
> Unify client and server certificate selection text

- draft-ietf-tls-rfc8446bis.md
Supported Groups is intimately tied to Key Share, where Key Share must be sent in the preference order specified by Supported Groups. 
Duplicate Key Shares for a group are already forbidden from being sent, but allowing duplicates in Supported Groups makes this a bit muddled if supported groups is permitted to be, for example,  ABA and the client sends key share B then A.  
Now, nothing sane should actually be sending duplicate supported groups in a preference order, but it's still not forbidden to do so today. I'm suggesting we just not allow this so server side implementations can reject attempts to do so.
> Forbid the sender from sending duplicate supported groups entries.

- draft-ietf-tls-rfc8446bis.md
Otherwise we run into the issue described in issue #1341.
Fixes #1341
> Forbid the sender from sending redundant update_requested KeyUpdates

- draft-ietf-tls-rfc8446bis.md
Remove normative references to paywalled crypto with the open access SP 800-56A [KEYAGREEMENT], which is already referenced for ECC public key validation.
Paywalled crypto specifications is a cybersecurity risk and goes against everything the IETF stands for. People should not have to pay to implement or analyze TLS 1.3.
Removed text on parameter generation as all the curves are named curves. This is likely a left over from an earlier version of TLS.
An alternative/additional open-access reference for ECC key generation and shared secret calculation would be SECG SEC 1.
> Remove normative references to paywalled crypto
